### ISSUE TITLE
Some options cannot be set from command line

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#106]
# CFR version
0.149-SNAPSHOT (commit da9725ba)

# Description
It appears some options cannot be set from command line because they do not appear in the list returned by `OptionsImpl.CFRFactory.getArguments()`.

- `OptionsImpl.FORCE_AGGRESSIVE_EXCEPTION_AGG2` (Note: This has the same option name as `FORCE_AGGRESSIVE_EXCEPTION_AGG`: `aexagg`)
- `OptionsImpl.FORCE_TOPSORT_NOPULL`
- `OptionsImpl.STATIC_INIT_RETURN`
- `OptionsImpl.LOMEM`

**Comment by leibnitz27** [comment]
*cough* low hanging fruit *cough*.

Though I did get bored of maintaining it.  ;)

**Comment by leibnitz27** [comment]
I admit - I was being terribly lazy. :)
