### ISSUE TITLE
Inner class of of generic class is not emitted in type usage

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#118]
# CFR version
0.149-SNAPSHOT (commit 55ea1b6)

# Compiler
javac 11.0.5

# Description
When a generic class contains an inner class (non-static) and that inner class is used as type, then the decompiled output only contains the generic outer.

Note: This can also cause a `NullPointerException` when the inner is annotated with a `TYPE_USE` annotation because the path iterator tries to access the inner class which is erroneously not present.

Source:
```
class GenericClassInner<T> {
    class Inner { }
    
    Inner a;
    
    void test(Inner a) { }
    
    Inner test() {
        return null;
    }
}
```

Decompiled output:
```
class GenericClassInner<T> {
    GenericClassInner<T> a;

    GenericClassInner() {
    }

    void test(GenericClassInner<T> genericClassInner) {
    }

    GenericClassInner<T> test() {
        return null;
    }

    class Inner {
        Inner() {
        }
    }
}
```

**Comment by leibnitz27** [comment]
Oh this one has opened all sorts of pain.  I can't believe I never noticed this. 
Thanks.  (Multiple tests added GenericInnerTest*)
