### ISSUE TITLE
Question: how to find lambda code at runtime using CFR?

### ISSUE THREAD

**Issue by rdehuyss** [leibnitz27/cfr#119]
Hi,

first time user of this CFR library... 

I have a problem where at runtime, I want to know the actual code of a lambda. An example:

Let's say we have the following code:
```
private Worker worker = new Worker();

public void runLambda() {
    myLibrary.doWork(() -> worker.doWork());
}
```

I'm interested in finding out this peace of code: `worker.doWork()` at runtime (e.g. users will use my library, use some lambda's, and I want to find out what lambda they passed to my library). Since the lambda they pass is Serializable, I already know the `implMethodName`, e.g.: `lambda$runLambda$81c80a4a$1` using SerializedLambda... but how to then get access to the actual method within the lambda?

I know it is possible using CFR (debugged through it quite a lot to find a hint on how to do this) but in my opinion, I did not find a good way to do so.

Thanks in advance,
Ronald

**Comment by Lanchon** [comment]
it is not your business what is inside lambdas that get passed to your library, only the signature matters to you and you already defined that. it is very rude to reverse callers of your library. your job is to design a library API that is clean and doesnt require hacks. what problem are you trying to solve with this reversing?

**Comment by Col-E** [comment]
Are you trying to determine that the method call in the lambda is `com/whatever/Worker.doWork()V`?

Or do you want the source code _(decompiled)_of the lambda they passed? So: `worker.doWork()`

**Comment by rdehuyss** [comment]
@Col-E I would prefer the fully qualified class name + method name & signature.

**Comment by Col-E** [comment]
Could you be more specific about the access you have to the lambda? If you have the class file where the `myLibrary.doWork(...)` is called, you can easily get all the information you need with any class file parser library.

**Comment by leibnitz27** [comment]
Ok - first - this really isn't a CFR thing ;)  

CFR is entirely about *NOT* using reflection, or any other such thing, or relying on the vagiaries of a particular JVM implementation - it's about static analysis of bytecode.  I strongly agree with @Lanchon ....  

To state the obvious - a functional interface implementation *may* be a lambda, or it may be... any old thing.  I assume you've already covered the non-lambda case.

I can't stress enough that if you rely on this sort of thing in production code, you're going to be basically buggered.

```
import java.io.Serializable;
import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Method;
import java.security.AccessController;
import java.security.PrivilegedExceptionAction;

public class HackedName {
    interface Foo extends Serializable {
        void accept(int i);
    }

    private static void doFoo(Foo f) throws Exception {
        Method m = f.getClass().getDeclaredMethod("writeReplace");
        m.setAccessible(true);
        SerializedLambda sl = (SerializedLambda) AccessController.doPrivileged((PrivilegedExceptionAction<Method>) () -> m).invoke(f);
        System.out.println("This lambda came from " + sl.getImplClass() + "::" + sl.getImplMethodName());
    }

    public static void main(String...args) throws Exception {
        doFoo(x -> { System.out.println(" first, "); System.out.println(x); });
        doFoo(x -> { System.out.println(" then, "); System.out.println(x); });
    }
}
```

**Comment by rdehuyss** [comment]
Well, you guys are correct... 

The thing I need it for is as follows (only Java 8 and higher support is needed):
In case of my first example: I want to catch the lambda, find the actual code inside (in this `worker.doWork()`), serialize it, send it to another physical machine where it then gets executed without the actual context (so, no use of `getImplMethodName` as this only specifies the context, the surrounding class could even not be available) but with the `Worker` class available.

Not a trivial task, I know. But thanks to @Col-E , I have some new insights.

Thank you all for the excellent support!
