### ISSUE TITLE
deobfuscation methodology

### ISSUE THREAD

**Issue by sjpotter** [leibnitz27/cfr#123]
A common form of obfuscation is basically just a set of static functions that process a string

pardon the pseudo code

```
public static String c::a() {
   return a.a();
}

public static String a::a() {
   return d.a();
}

public static String d::a() {
   return "Hello World";
}
```

it be interesting if the obfuscation could short circuit a::a() and just go directly to d::a()  i.e. if the initial return a.a() could be replaced with `return "Hello World";`

more complicated would be boolean obfuscation, where one one might
```
public static bool a::a() {
    return b.a();
}

public static bool b::a() {
   return !c.a();
}

public static bool c::a() {
   return !d.a()
}
```

it also be interesting if it could short circuit this, while collapsing the inversions.  i.e. it be interesting if it could replace the `return b.a()` with `return d.a()` (or if there was another boolean inversion before it, `return !d.a()`

**Comment by Lanchon** [comment]
cfr is not a deobfuscator and it should never do this IMHO. if you want to deobf, run your code through a deobf before feeding it to cfr.

**Comment by sjpotter** [comment]
I didn't even know that existed.  I'll try it out

**Comment by Lanchon** [comment]
if it doesnt you can make it yourself, with libraries such as ASM. but take a look at soot instead: http://sable.github.io/soot/

**Comment by leibnitz27** [comment]
Yeah, I have to agree with lanchon on this - deobfuscating to this level would be changing the semantics of individual classes (in the absence of other classes).  

While this is definitely a good thing to do when analyzing an obfuscated application, it's not really what CFR is for - and adding it would rather go against the (sorry, I keep quoting it) unix philosophy.   

Closing this as 'won't fix'.
