### ISSUE TITLE
Enums initialized with switch expression are decompiled as regular class

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#129]
# CFR version
0.150-SNAPSHOT (commit cf242d2)

# Compiler
javac 14

# Description
Relates to #128

Decompiling an enum whose values are using switch expressions (Java 14 feature) for initialization results in a regular class which `extends Enum`, which is invalid code.

Source:
```
enum SwitchEnumConstructorTest {
    A(switch(0) {
        case 0 -> 1;
        default -> 2;
    }),
    B(switch(0) {
        case 0 -> 3;
        default -> 4;
    });
    
    private SwitchEnumConstructorTest(int a) { }
}
```

Decompiled output:
```
final class SwitchEnumConstructorTest
extends Enum<SwitchEnumConstructorTest> {
    public static final /* enum */ SwitchEnumConstructorTest A;
    public static final /* enum */ SwitchEnumConstructorTest B;
    private static final /* synthetic */ SwitchEnumConstructorTest[] $VALUES;

    public static SwitchEnumConstructorTest[] values() {
        return (SwitchEnumConstructorTest[])$VALUES.clone();
    }

    public static SwitchEnumConstructorTest valueOf(String string) {
        return Enum.valueOf(SwitchEnumConstructorTest.class, string);
    }

    private SwitchEnumConstructorTest(int n2) {
    }

    static {
        int n = switch (0) {
            case 0 -> 1;
            default -> 2;
        };
        A = new SwitchEnumConstructorTest(n);
        int n2 = switch (0) {
            case 0 -> 3;
            default -> 4;
        };
        B = new SwitchEnumConstructorTest(n2);
        $VALUES = new SwitchEnumConstructorTest[]{A, B};
    }
}
```

**Comment by leibnitz27** [comment]
C:\code\cfr\target\classes>java org.benf.cfr.reader.Main c:\code\cfr_tests\output\java_14\org\benf\cfr\tests\SwitchEnumConstructorTest.class
/*
 * Decompiled with CFR <Could not determine version>.
 */
package org.benf.cfr.tests;

enum SwitchEnumConstructorTest {
    A(switch (0) {
        case 0 -> 1;
        default -> 2;
    }),
    B(switch (0) {
        case 0 -> 3;
        default -> 4;
    });


    private SwitchEnumConstructorTest(int a) {
    }
}
