### ISSUE TITLE
how to output all file in jar

### ISSUE THREAD

**Issue by Ares-X** [leibnitz27/cfr#141]
i use command `cfr -jar xxx.jar --outputdir ./src` 

![image](https://user-images.githubusercontent.com/30471149/79683326-d414f700-825b-11ea-9a26-d79b7a286614.png)

but some file was lost,how to output all files in jar?

**Comment by leibnitz27** [comment]
CFR just decompiles classfiles to java.

If you want to extract other files from the jar, just rename the jar to zip, and unzip it.

(A jar is just a zip file with a different extension).
