### ISSUE TITLE
Deobfuscation of inner class throws NullPointerException

### ISSUE THREAD

**Issue by RibozymeR** [leibnitz27/cfr#144]
Compiling the code

    package net;
    import java.util.function.IntFunction;  
    public class Test {
        public IntFunction<Inter[]> func() {
            return Inter[]::new;
        }
        static interface Inter { }
    }

with javac 12.0.2, remapping

    net.Test$Inter -> Test$Kinter

then decompiling with CFR version 0.149 using --obfuscationpath gives

    package net;
    import java.util.function.IntFunction;
    public class Test {
        public IntFunction<Kinter[]> func() {
            return Kinter[]::}

and throws NullPointerException ([Stacktrace](https://github.com/leibnitz27/cfr/files/4512427/log.txt)).

**Comment by leibnitz27** [comment]
can you provide the obfuscation remapper file you used?

**Comment by RibozymeR** [comment]
Of course; it was literally nothing but the line

    net.Test$Inter -> Test$Kinter:

**Comment by leibnitz27** [comment]
Nice.   Blew as there's no actual prototype for an array new ( []::new) to deobfuscate.  Fixed on master.
