### ISSUE TITLE
Option to automatically handle conditional jumps that are actually unconditional

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#145]
CFR decompiles senseless `if`s like `iconst_0
iconst_0
if_icmpne L5
` to
```java        
 if (0 == 0) {
            //this always happens
 }
```
Please add an option to automatically handle unnecessary if instructions (interpret them as `goto`, or not). This makes (poorly) obfuscated code easier to read without changing the instructions.

**Comment by leibnitz27** [comment]
Got a (legally) usable example?  There's a few points where I could check for tautologies, it might be interesting to see which produces what.

In general I prefer not to add deliberate anti-obfuscation if legit java can be produced from the byte code,  however I can imagine it wouldn't be too hard to produce spaghetti using this which is harder to unwind without a tautology check, so it'd be nice to have an in-the-wild example that fails (or a simalcrum of one at least ;) ).

**Comment by GraxCode** [comment]
I used a .class file of CFR itself to create an example (hope that's not a problem to you). This time, a local variable that stays null the whole code is used as dummy (and compared with ifnonnull). CFR fails to decompile the second method. 
[CfrDriverImpl.zip](https://github.com/leibnitz27/cfr/files/4525309/CfrDriverImpl.zip)

**Comment by GraxCode** [comment]
If you only have direct comparisons in mind (`aconst_null ifnonnull`), you can replace the var loads with `aconst_null`. It will result in the same output.

**Comment by Col-E** [comment]
Without opaque predicates: [YodaHelloWorld.class.txt](https://github.com/leibnitz27/cfr/files/4602382/YodaHelloWorld.class.txt)

```java
public class YodaHelloWorld {
    /*
     * Enabled force condition propagation
     * Lifted jumps to return sites
     */
    public static void main(String[] arrstring) {
        System.out.println("Hello World");
    }
}
```

With opaque predicates:  [OpaqueYodaHelloWorld.class.txt](https://github.com/leibnitz27/cfr/files/4602381/OpaqueYodaHelloWorld.class.txt)

```java
import java.io.PrintStream;

public class OpaqueYodaHelloWorld {
    /*
     * Enabled force condition propagation
     * Lifted jumps to return sites
     */
    public static void main(String[] arrstring) {
        if (false) {
            return;
        }
        PrintStream printStream = System.out;
        if (printStream == null) {
            // empty if block
        }
        if (-1 != -1) {
            // empty if block
        }
        printStream.println("Hello World");
    }
}
```

**Comment by leibnitz27** [comment]
So, here's fun - there's only one tautology in your class file - 

```
17.5.4. Write-protected Fields
Normally, a field that is final and static may not be modified. However, System.in, System.out, and System.err are static final fields that, for legacy reasons, must be allowed to be changed by the methods System.setIn, System.setOut, and System.setErr
```

So I could use my sneaky obfuscator to do this:

```
public class OutNotConstantTest {
    public static void main(String ... args) {
        doAthing();
        System.setOut(null);
        doAthing();
    }

    private static void doAthing() {
        PrintStream ps = System.out;
        if (ps == null) {
            System.err.println("You've found it!");
        } else {
            System.err.println("Nothing to see.");
        }
    }
}
```

**Comment by Lanchon** [comment]
we all know even static final fields may be modified. IMHO whole program analysis requiered to infer the value of a field is a big no for CFR: the decompilation of a class should be valid even if other classes are changed. (this is why i dislike some renaming done in CFR.) if javac doesnt do it, most likely CFR shouldnt reverse it. resolving tautologies depending on field values is IMHO strictly the realm of bytecode deobfuscators. (and most renaming is too.) i think javac resolves simple tautologies so they should only be found in bytecode produced by other tools. besides enhancing general decompilation, another argument for removing simple tautologies is that they can't be expressed in java in a way that javac will output them, so why keep them at all. if only for the purpose of documenting bytecode, then comments could be emitted instead.

**Comment by leibnitz27** [comment]
I'm actually ok with removing entirely trivial tautologies/oxymorons which don't require program analysis - so, for example, I'm DEFINITELY not ok with
```
a = 1
if (a < 2) {
  foo
}
```

Even though it's entirely obvious.  (I should note, I do perform some limited program analysis, because without it Kotlin generates absolute junk sometimes - so following a conditional chain with literals is sometimes necessary).

however, ` if (explicit literal integer condition involving no variables) ` seems like a reasonable thing to handle in a "heavy" fallback pass, i.e. it's all gone completely wrong, so let's have a go at removing impossible code in case it's making something look like a loop when it isn't.  (at this point it's usually all about trying to de-spaghettify code)

**Comment by leibnitz27** [comment]
(should mention ` --removedeadconditionals true ` required, unless it's triggered in a recovery pass.
