### ISSUE TITLE
Decompile DCMP, FCMP and LCMP

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#146]
CFR doesn't decompile compare instructions that are not linked with jumps.
Decompiler output:
```java
    public static int compareLongs(long l1, long l2) {
        return (int)(l1 LCMP l2);
    }
```
It should be
```java
    public static int compareLongs(long l1, long l2) {
        return (int)Long.compare(l1, l2);
    }
```
or
```java
    public static int compareLongs(long l1, long l2) {
        return l1 == l2 ? 0 : (l2 < l1 ? 1 : -1);
    }
```
The same for double and float comparison. 
[lcmp-test.zip](https://github.com/leibnitz27/cfr/files/4525463/lcmp-test.zip)

**Comment by leibnitz27** [comment]
Oh, haha, I love it.  I'd left those in early on as a hint that I'd failed to roll up, but absolutely that's legit.  Nice.

**Comment by leibnitz27** [comment]
Fixed on master.  Thanks, that was interesting.

FWIW - the d/f comparisons require an interesting tweak - attached an example which demonstrates it (and generates the correct output if you use this commit).

[Compare.class.txt](https://github.com/leibnitz27/cfr/files/4527920/Compare.class.txt)
