### ISSUE TITLE
Decompile handle LDCs

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#149]
[NewLDCTypes.class.txt](https://github.com/leibnitz27/cfr/files/4536629/NewLDCTypes.class.txt)
Currently, CFR fails to decompile Handle ldcs. 
```
 /*
         * This method has failed to decompile.  When submitting a bug report, please provide this stack trace, and (if you hold appropriate legal rights) the relevant class file.
         * org.benf.cfr.reader.util.ConfusedCFRException: Expecting a ConstantPoolEntryLiteral or ConstantPoolEntryDynamicInfo
         * org.benf.cfr.reader.bytecode.opcode.OperationFactoryLDC.getStackType(OperationFactoryLDC.java:37)
         * org.benf.cfr.reader.bytecode.opcode.OperationFactoryLDC.getStackDelta(OperationFactoryLDC.java:18)
         * org.benf.cfr.reader.bytecode.opcode.JVMInstr.getStackDelta(JVMInstr.java:315)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.Op02WithProcessedDataAndRefs.populateStackInfo(Op02WithProcessedDataAndRefs.java:195)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.Op02WithProcessedDataAndRefs.populateStackInfo(Op02WithProcessedDataAndRefs.java:1542)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:393)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:251)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:185)
         * org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:94)
         * org.benf.cfr.reader.entities.Method.analyse(Method.java:521)
         * org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:1035)
         * org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:922)
         * org.benf.cfr.reader.Driver.doJarVersionTypes(Driver.java:252)
         * org.benf.cfr.reader.Driver.doJar(Driver.java:134)
         * org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:65)
         * org.benf.cfr.reader.Main.main(Main.java:49)
         */
```

It could possibly be decompiled to
 ```java
MethodHandles.lookup().findStatic(<owner>.class, "<name>",
				MethodType.fromMethodDescriptorString("<desc>", <owner>.class.getClassLoader())) // findStatic can be exchanged with findVirtual, etc. depending on the handle opcode
```
Only problem is that the method throws a bunch of exceptions.
Maybe add a setting to decompile handle ldcs or just leave it a `null /** handle toString here **/`

**Comment by ItzSomebody** [comment]
I believe this is may also be applicable for the `ldc`-ing of `MethodType` as well.

**Comment by leibnitz27** [comment]
Out of interest - what do you use to construct these?   I mostly stick to jasmin, which is horribly outdated like me ;)

**Comment by leibnitz27** [comment]
It seems (I may well be wrong) that

```
            public MethodHandle handleLDC() {
                return (
                        ((Supplier<MethodHandle>)() -> {
                            try {
                                return MethodHandles.lookup().findStatic(NewLDCTypes.class, "handle", MethodType.fromMethodDescriptorString("(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/invoke/MutableCallSite;Ljava/lang/String;)Ljava/lang/Object;", null));
                            } catch (NoSuchMethodException | IllegalAccessException e) {
                                throw new RuntimeException(e);
                            }
                        }).get()
                ).asFixedArity();
            }

```

would be a legitimate decompilation of handleLDC.

Note - I don't think this is the nicest thing to do - if I've understood right above, it would be better to do something like emit a helper interface + method

```

    interface CFR_HANDLE_LDC<T> {
        T get() throws NoSuchMethodException, IllegalAccessException;
    }

    private static <T> T cfr_handle_ldc(CFR_HANDLE_LDC<T> s) {
        try {
            return s.get();
        } catch (NoSuchMethodException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
    
    public MethodHandle handleLDC() {
        return (cfr_handle_ldc(
                () -> MethodHandles.lookup().findStatic(NewLDCTypes.class, "handle", MethodType.fromMethodDescriptorString("(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/invoke/MutableCallSite;Ljava/lang/String;)Ljava/lang/Object;", null)))
        ).asFixedArity();
    }
```

This is more verbose OUTSIDE of the method, but has several benefits - 

* turns it into a lambda expression ( CFR can't handle lambda bodies this early, would require some very painful refactoring).
* makes it obvious where CFR has faked up support.
* reduces potentially duplicated verbiage.

**Comment by GraxCode** [comment]
> 
> 
> Out of interest - what do you use to construct these? I mostly stick to jasmin, which is horribly outdated like me ;)

I'm using an (old) tool of mine: https://github.com/GraxCode/JByteMod-Beta/ Very easy to use and produce nasty bytecode

**Comment by GraxCode** [comment]
> 
> 
> It seems (I may well be wrong) that
> 
> ```
>             public MethodHandle handleLDC() {
>                 return (
>                         ((Supplier<MethodHandle>)() -> {
>                             try {
>                                 return MethodHandles.lookup().findStatic(NewLDCTypes.class, "handle", MethodType.fromMethodDescriptorString("(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/invoke/MutableCallSite;Ljava/lang/String;)Ljava/lang/Object;", null));
>                             } catch (NoSuchMethodException | IllegalAccessException e) {
>                                 throw new RuntimeException(e);
>                             }
>                         }).get()
>                 ).asFixedArity();
>             }
> ```
> 
> would be a legitimate decompilation of handleLDC. (the lambda may look silly but makes more sense given below). It also keeps to a single statement, which is very handy.
> 
> Note - I don't think this is the nicest thing to do - if I've understood right above, it would be better to do something like emit a helper interface + method
> 
> ```
> 
>     interface CFR_HANDLE_LDC<T> {
>         T get() throws NoSuchMethodException, IllegalAccessException;
>     }
> 
>     private static <T> T cfr_handle_ldc(CFR_HANDLE_LDC<T> s) {
>         try {
>             return s.get();
>         } catch (NoSuchMethodException | IllegalAccessException e) {
>             throw new RuntimeException(e);
>         }
>     }
>     
>     public MethodHandle handleLDC() {
>         return (cfr_handle_ldc(
>                 () -> MethodHandles.lookup().findStatic(NewLDCTypes.class, "handle", MethodType.fromMethodDescriptorString("(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/invoke/MutableCallSite;Ljava/lang/String;)Ljava/lang/Object;", null)))
>         ).asFixedArity();
>     }
> ```
> 
> This is more verbose OUTSIDE of the method, but has several benefits -
> 
>     * turns it into a lambda expression ( CFR can't handle lambda bodies this early, would require some very painful refactoring).
> 
>     * makes it obvious where CFR has faked up support.
> 
>     * reduces potentially duplicated verbiage.

I would like something like that more, as I do not favor the creation of new classes:
```java
    MethodHandle cfr_method_handle = null; // construct a new local and add a comment to the method "warning: method handle ldc"
    try {
      cfr_method_handle = MethodHandles.lookup().findStatic(NewLDCTypes.class, "handle",
          MethodType.fromMethodDescriptorString("(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/invoke/MutableCallSite;Ljava/lang/String;)Ljava/lang/Object;", null));
    } catch (IllegalAccessException | NoSuchMethodException e) {
      throw new IllegalStateException(e);
    }
    // continue code here
```
I think lambdas make it harder to understand the code and this solution is more "clean" and easier to implement. Another possible way would be this:
```java
    MethodHandle cfr_method_handle = null;
    try {
      cfr_method_handle = MethodHandles.lookup().unreflect(NewLDCTypes.class.getDeclaredMethod("handle", MethodHandles.Lookup.class, ...));
    } catch (IllegalAccessException | NoSuchMethodException e) {
      throw new IllegalStateException(e);
    }
``` 
The only disatvantage here would be code duplication, but i don't think this would occur in any case

**Comment by leibnitz27** [comment]
The pain here is that the point at which this is being processed, the constant is an rvalue.  

There's the inevitable usage of these as chained constructor arguments, which means that they can't be turned into multiple statements.  

(also, Introducing exception blocks at this stage in the pipeline is something I don't want to do right now, as it would seriously screw with later pipeline stages. )

```
class Foo : Bar {
public Foo() {
   super(ldc methodhandle, ldc methodhandle, ldc methodhandle);
   STUFF!
}

```
Essentially there's two solutions that will work in the general case - (a) lambdas with helper methods, or (b) emit-a-new-fake-method-with-its-own-exception-handling per LDC.  

I'm starting to lean a little towards (b).

**Comment by GraxCode** [comment]
I think the new method is probably the best solution.
