### ISSUE TITLE
Same object reference but with checkcast on monitors

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#154]
Decompiling this bytecode using the latest build
```
             invokestatic Sample.monitorReference()Ljava/lang/Object;
             dup
             dup
             dup
             checkcast java/lang/Class
             monitorenter
             swap
             invokestatic Sample.shouldBeInside()V
             monitorexit
             invokestatic Sample.shouldBeOutside()V
             areturn
```
leads to this code:
```java
    public Object confusingMonitors() {
        Object object = Sample.monitorReference();
        Object object2 = object;
        synchronized ((Class)object) {
            Sample.shouldBeInside();
            // ** MonitorExit[v0] (shouldn't be in output)
            Sample.shouldBeOutside();
            return object;
        }
    }
```
it should actually be
```java
    public Object confusingMonitors() {
        Object object = Sample.monitorReference();
        synchronized ((Class)object) {
            Sample.shouldBeInside();
        }
        Sample.shouldBeOutside();
        return object;
    }
```
The checkcast confuses CFR as it thinks it isn't exiting the monitor on the same object, while checkcast actually returns the same object during execution. Removing it leads to correct decompilation.

**Comment by leibnitz27** [comment]
It's actually even more fun than that - what if the cast is on the exit? :)

[CheckcastMonitor2.class.txt](https://github.com/leibnitz27/cfr/files/4579630/CheckcastMonitor2.class.txt)
[CheckcastMonitor.class.txt](https://github.com/leibnitz27/cfr/files/4579631/CheckcastMonitor.class.txt)

**Comment by leibnitz27** [comment]
Of course, they're silly examples, but CheckCastMonitor2 is particularly fun.

```
/*
 * Decompiled with CFR <Could not determine version>.
 */
class CheckcastMonitor {
    public static void main(String[] arrstring) {
        CheckcastMonitor checkcastMonitor = new CheckcastMonitor();
        synchronized ((String)((Object)checkcastMonitor)) {
            System.out.println("HELLO WORLD");
        }
        System.out.println("GOODBYE WORLD");
    }
}

class CheckcastMonitor2 {
    public static void main(String[] arrstring) {
        CheckcastMonitor2 checkcastMonitor2 = new CheckcastMonitor2();
        synchronized (checkcastMonitor2) {
            System.out.println("HELLO WORLD");
            String cfr_ignored_0 = (String)((Object)checkcastMonitor2);
        }
        System.out.println("GOODBYE WORLD");
    }
}
```

**Comment by leibnitz27** [comment]
In general, I don't think it's ever going to be possible to undo all the horrid screwing around people could do with monitors.

(for example, a 2 pass loop in which you enter on pass 1, exit on pass 2 :( )

**Comment by GraxCode** [comment]
The best way to handle this is probably to comment monitors that are not decompilable to a synchronized block. Same with nested try catch blocks. Very interesting the bytecode verifier does not check that.

**Comment by leibnitz27** [comment]
Indeed - this is the current behaviour.
