### ISSUE TITLE
Unnecessary do loop around return statement

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#155]
[WeirdDo.class.txt](https://github.com/leibnitz27/cfr/files/4600766/WeirdDo.class.txt)
Decompiling this class leads to weird code.
```java
    /*
     * Enabled force condition propagation
     * Lifted jumps to return sites
     */
    public int action(boolean other) {
        if (other) return 1;
        {
            if (0 > 0) {
                return 0;
            }
            do {
                return 1;
                break;
            } while (true);
        }
    }
```
Code doesn't compile in eclipse due to the break after the return. (Also, are the braces after the first if intended?)

**Comment by leibnitz27** [comment]
amusingly, this generates very nice code if earlier passes bomb out - if we explicitly force recovery pass 2...

```
C:\code\cfr\target\classes>java org.benf.cfr.reader.Main c:\Downloads\WeirdDo.class --recpass 2
/*
 * Decompiled with CFR <Could not determine version>.
 */
public class WeirdDo {
    /*
     * Enabled aggressive block sorting
     */
    public int action(boolean other) {
        if (other) return 1;
        if (0 <= 0) return 1;
        return 0;
    }
}```

but the first recovery pass generated what looked 'good enough' (and its always best to stick with fewer aggressive transforms).

Anyway - those behaviours are both kind of unambiguously gross, so fixed, thanks.

```
C:\code\cfr\target\classes>java org.benf.cfr.reader.Main c:\Downloads\WeirdDo.class
/*
 * Decompiled with CFR <Could not determine version>.
 */
public class WeirdDo {
    /*
     * Enabled force condition propagation
     * Lifted jumps to return sites
     */
    public int action(boolean other) {
        if (other) return 1;
        if (0 > 0) {
            return 0;
        }
        return 1;
    }
}
```
