### ISSUE TITLE
Single method decompilation fails local-variable-reconstruction

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#16]
By using the "methodname" option to decompile only a single method
`label 1
iconst_0
ireturn
label 2`
gets decompiled to
`public final boolean isEmpty( var1_1) {
    return false;
}
`
using CFR 0.146

Maybe because the local variable is never referenced?

**Comment by leibnitz27** [comment]
Can you attach a test class? Thanks.

**Comment by leibnitz27** [comment]
(i.e. does not manifest with (zipped) simple class.

[NoName.zip](https://github.com/leibnitz27/cfr/files/3415885/NoName.zip)

(Note that in my example method is static, as it has no this pointer).

**Comment by leibnitz27** [comment]
Ping @GraxCode ;)

**Comment by leibnitz27** [comment]
ping @GraxCode  - are you able to provide sample?

**Comment by leibnitz27** [comment]
Closing this issue as not-reproducible, and dead.   If anyone wants to reopen with a sample, please attach.
