### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#160]
What do you think about adding issue templates (see [GitHub help article](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository))?

They would allow defining an issue description which could then indicate to the issue creator which information they have to provide, e.g. CFR version and compiler version.
Additionally issue templates can automatically add labels, so you could for example create two templates, one for bugs and one for feature requests. However, users are by default not restricted to these and can still create a normal issue if they think none of the templates matches their issue.

Would you like me to create an example pull request for it?

**Comment by leibnitz27** [comment]
Seems like a perfectly reasonable plan. :)

thanks
