### ISSUE TITLE
--removedeadswitchcases

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#162]
Imagine a switch like this:
```java
      switch (1) {
      default: {
        return false;
      }
      case 1:
        return true;
      }
```
or
```java
    switch (boolean) { //illegal in java, legal in bytecode
    case 0:
      return false;
    case 1:
      return true;
    case 2:
    case 3:
    case 4:
    ...
      //never executed, remove it from the graph
      //an obfuscator could convert ifeq / ifne to switch and then add redundant extra cases
      //imagine a goto random label for each extra case
    default:
      //also not executed if both cases are handled
    }
```
I think there can be done a lot of optimization / obfuscation removal. Also not bad for a second pass.

**Comment by leibnitz27** [comment]
The former I can see as realistic, though I doubt anyone's going to bother with an obfuscation so trivial. (Unless it's @Marcono1234 generating psychotic switch expression examples)

The latter I'm *really* not keen on.  We simply dont know at the bytecode level if something *is* a bool or not - you could declare it a bool parameter then assign 3 - while I try to infer the type/domain, it's very possible to get it wrong.

(As an aside, abused booleans can lead to different results in different jvms, I have some tests somewhere I believe)

**Comment by leibnitz27** [comment]
An example of where this will potentially break legit code (i.e. you can't always just remove a pointless switch)

https://github.com/leibnitz27/cfr_tests/blob/master/src_14/org/benf/cfr/tests/SwitchConstructorTest7.java

**Comment by GraxCode** [comment]
Haven't worked with new switch statements yet, but looks ugly

**Comment by GraxCode** [comment]
Didn't know you could do that with new switches. You can close it if you want.

**Comment by leibnitz27** [comment]
By the way - this is an excellent example of booleans behaving badly:

[BooleanArrayTest.class.txt](https://github.com/leibnitz27/cfr/files/4617282/BooleanArrayTest.class.txt)

Original submitter isn't on github I think (Hi Abe!).

Generates different output on jvm6 vs others, just to mess with you ;)

**Comment by leibnitz27** [comment]
Ok - I'm going to close this for now.   There's potentially some value in trying to add a last gasp recovery pass to do this, but it's certainly not the sort of thing you'd want to be doing normally.
