### ISSUE TITLE
Change do {} while(true) to while(true) {}

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#167]
These loops in CFR output
```java
do {
...
} while(true);
```
should be changed to
```java
while(true) {
...
} 
```
A do while loop insists that the condition is at the end and when I encounter a loop the first thing I want to know is what the condition is. Thus, I am forced to look for the end of the code block of the loop just to find out it is an infinite loop. In conclusion, changing those loops to while loops will improve readability.

**Comment by leibnitz27** [comment]
You know, I was going to die on this hill ;)  (especially because it's subjective)

Alas, I put this to a straw poll of 1000 java devs ( closed audience ) and lost 10:1 (with one person demanding `for(;;)` )

So, fair enough.

But out of sheer (1/schadenfreude) I'll close https://github.com/leibnitz27/cfr/issues/17 .   Because THAT HILL IS MINE TO DIE ON. ;)

**Comment by Lanchon** [comment]
lol noooo, THAT guy is right, `for (;;)` is the idiomatic way!

(seriously, i do that; it's less verbose and there is no condition to look at.)

**Comment by Lanchon** [comment]
but i do agree on `do {} while(true)` being the least desirable form.

**Comment by GraxCode** [comment]
hehe - I mean you could still make an interface that lets somebody use their own formatting standards (please don't)

**Comment by GraxCode** [comment]
> lol noooo, THAT guy is right, `for (;;)` is the idiomatic way!
> 
> (seriously, i do that; it's less verbose and there is no condition to look at.)

Oh hell no, it doesn't look aesthetic and an amateur wouldn't understand it imo

**Comment by Col-E** [comment]
> lol noooo, THAT guy is right, `for (;;)` is the idiomatic way!

I got a better one :wink: 

```java
label-begin: {
    // code here
    goto label-begin
}
```

**Comment by GraxCode** [comment]
> > lol noooo, THAT guy is right, `for (;;)` is the idiomatic way!
> 
> I got a better one 
> 
> ```java
> label-begin: {
>     // code here
>     goto label-begin
> }
> ```

Looks like krakatau

**Comment by Lanchon** [comment]
its inevitable, CFR will have to be hostile-forked now

**Comment by leibnitz27** [comment]
> I got a better one 😉
> 
> ```java
> label-begin: {
>     // code here
>     goto label-begin
> }
> ```

FWIW this is why I prefer the while(true) ;) - it's clearly a goto at the end of the block.

**Comment by GraxCode** [comment]
> > I got a better one wink
> > ```java
> > label-begin: {
> >     // code here
> >     goto label-begin
> > }
> > ```
> 
> FWIW this is why I prefer the while(true) ;) - it's clearly a goto at the end of the block.

If you'd make a statistic of what is used most, while(true) {} will probably win by far. Also oracle docs specify while(true) {} as infinite loop: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/while.html

**Comment by leibnitz27** [comment]
> hehe - I mean you could still make an interface that lets somebody use their own formatting standards (please don't)

FWIW - I already mentioned this in #17 - If someone wants to bolt a code-style plugin on afterwards, feel free, but that's definitely not a reasonable thing to incorporate.
