### ISSUE TITLE
'First' condition for unusual jump targeting inside of loop decompiled wrongly

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#174]
# CFR version
499f6d3b2e431bc647e1f4c1799ec178c8e9e600

# Compiler
java 8 and few modifications

# Description
Actual (pseudo-)code:
```java
   public static void uglyFlow() {
      if (x == 0) {
         goto Label;
      }
      System.out.println("x is not 0");
      while(true) {
         System.out.println("1");
         System.out.println("2");
         Label: {
            System.out.println("3");
         }
      }
   }
```

Decompiled to wrong code:
```java
    /*
     * Handled impossible loop by adding 'first' condition
     * Enabled aggressive block sorting
     */
    public static void uglyFlow() {
        boolean bl = true;
        while (true) {
            block2: {
                if (!bl || (bl = false)) continue;
                if (x == 0) break block2;
                System.out.println("x is not 0");
                System.out.println("1");
                System.out.println("2");
            }
            System.out.println("3");
        }
    }
```
Wouldn't it be easier to just duplicate the end of the inside of the loop that is used? like:
```java
   public static void uglyFlow() {
      if (x == 0) {
         System.out.println("3");
      } else {
         System.out.println("x is not 0");
      }

      while(true) {
         System.out.println("1");
         System.out.println("2");
         System.out.println("3");
      }
   }
```
Would result in way cleaner code!
# Example
[DoubleDoJump.class.txt](https://github.com/leibnitz27/cfr/files/4673696/DoubleDoJump.class.txt)

**Comment by leibnitz27** [comment]
It's true, duplication results in cleaner code in this particular case, however what I *really* hate about that approach is that it's very susceptible to (what I'll call - there's probably a well defined name already) a code expansion attack.

Consider doing this, but at multiple callsites - 10x bottom part of loop (and let's make that bottom part large).

Then nest that inside the same approach.   100x repeat.

The only situation in which I think you can legitimately get away with inlining copied code is trying to represent behaviour of a JSR.

Consider this trivial example:
[LoopFakery3.class.txt](https://github.com/leibnitz27/cfr/files/4676225/LoopFakery3.class.txt)

**Comment by leibnitz27** [comment]
(Comedy fact, the other example of a code duplication attack that springs to mind is also related to JSRs).

Try compiling this:

```
public class ExpansionAttack {
    public static void main(String ... args) {
        try {
            switch (args.length) {
                case 1:
                    return;
                case 2:
                    return;
                case 3:
                    return;
                case 4:
                    return;
                case 5:
                    return;
                case 6:
                    return;
                case 7:
                    return;
                case 8:
                    return;
            }
        } finally {
            try {
                switch (args.length) {
                    case 1:
                        return;
                    case 2:
                        return;
                    case 3:
                        return;
                    case 4:
                        return;
                    case 5:
                        return;
                    case 6:
                        return;
                    case 7:
                        return;
                    case 8:
                        return;
                    case 9:
                        return;
                }
            } finally {
                try {
                    switch (args.length) {
                        case 1:
                            return;
                        case 2:
                            return;
                        case 3:
                            return;
                        case 4:
                            return;
                        case 5:
                            return;
                        case 6:
                            return;
                        case 7:
                            return;
                        case 8:
                            return;
                        case 9:
                            return;
                        case 10:
                            return;
                        case 11:
                            return;
                    }
                } finally {
                    System.out.println("This little piggy went to market");
                    System.out.println("This little piggy stayed at home");
                    System.out.println("This little piggy had roast beef");
                    System.out.println("This little piggy had none");
                    System.out.println("And this little piggy went weeeeeeeeeeeee all the way home");
                }
            }
        }
    }
}
```

**Comment by leibnitz27** [comment]
```
    public static void uglyFlow() {
        boolean bl = true;
        while (true) {
            block3: {
                block2: {
                    if (!bl || (bl = false)) break block2;
                    if (x == 0) break block3;
                    System.out.println("x is not 0");
                }
                System.out.println("1");
                System.out.println("2");
            }
            System.out.println("3");
        }
    }
```

**Comment by GraxCode** [comment]
You could check for a maximum amount of code to be duplicated. This way the simplicity of the code can be maintained, while also being prepared for such attacks.

**Comment by GraxCode** [comment]
> public class ExpansionAttack {
>     public static void main(String ... args) {
>         try {
>             switch (args.length) {
>                 case 1:
>                     return;
>                 case 2:
>                     return;
>                 case 3:
>                     return;
>                 case 4:
>                     return;
>                 case 5:
>                     return;
>                 case 6:
>                     return;
>                 case 7:
>                     return;
>                 case 8:
>                     return;
>             }
>         } finally {
>             try {
>                 switch (args.length) {
>                     case 1:
>                         return;
>                     case 2:
>                         return;
>                     case 3:
>                         return;
>                     case 4:
>                         return;
>                     case 5:
>                         return;
>                     case 6:
>                         return;
>                     case 7:
>                         return;
>                     case 8:
>                         return;
>                     case 9:
>                         return;
>                 }
>             } finally {
>                 try {
>                     switch (args.length) {
>                         case 1:
>                             return;
>                         case 2:
>                             return;
>                         case 3:
>                             return;
>                         case 4:
>                             return;
>                         case 5:
>                             return;
>                         case 6:
>                             return;
>                         case 7:
>                             return;
>                         case 8:
>                             return;
>                         case 9:
>                             return;
>                         case 10:
>                             return;
>                         case 11:
>                             return;
>                     }
>                 } finally {
>                     System.out.println("This little piggy went to market");
>                     System.out.println("This little piggy stayed at home");
>                     System.out.println("This little piggy had roast beef");
>                     System.out.println("This little piggy had none");
>                     System.out.println("And this little piggy went weeeeeeeeeeeee all the way home");
>                 }
>             }
>         }
>     }
> }
I still don't understand why they avoid jsr, that code is over 65kb. Verifying jsr shouldn't be a big problem if you think about it..

**Comment by GraxCode** [comment]
Another case where duplication could be very useful: 
[FromLoopToLoop.class.txt](https://github.com/leibnitz27/cfr/files/4676855/FromLoopToLoop.class.txt)
