### ISSUE TITLE
Handle eclipse special case string switch

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#176]
# CFR version
6d817c99333c3f691aeb00aa68cb71047ecf359e

# Compiler
OpenJDK 8

# Description
Decompiler outputs too many labels for this simple code. Also seems like string switches are not decoded, even when the option is set to true.
```java
    while (true) {
      switch (string) {
      case "apples":
        System.out.println("apples");
        break;
      case "pears":
        System.out.println("pears");
        break;
      }
    }
```
gets decompiled to
```java
        block4: while (true) {
            block6: {
                String string = SwitchInLoop.string;
                switch (string.hashCode()) {
                    case -1411061671: {
                        if (string.equals("apples")) break;
                        continue block4;
                    }
                    case 106540109: {
                        if (!string.equals("pears")) {
                            continue block4;
                        }
                        break block6;
                    }
                }
                System.out.println("apples");
                continue;
            }
            System.out.println("pears");
        }
```

# Example
[apples-n-pears.jar.txt](https://github.com/leibnitz27/cfr/files/4698065/apples-n-pears.jar.txt)

**Comment by leibnitz27** [comment]
Interesting - javac 8 generates significantly different bytecode, resulting in 

```
public class StringSwitchTest5 {
    public static void foo(String string) {
        while (true) {
            switch (string) {
                case "apples": {
                    System.out.println("apples");
                    break;
                }
                case "pears": {
                    System.out.println("pears");
                }
            }
        }
    }
}
```

**Comment by leibnitz27** [comment]
Hmm - nope - something's fishy here.  Is this a baseline openjdk?  Where did you get it from?

I've just compiled this with 

```
C:\code\cfr_tests>"c:\Program Files\Java\openjdk8\bin"\java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

and it generates identical code to jdk8, which works fine.

No doubt your bytecode is legit, but it doesn't look like the behaviour of project coin, it looks more like the kotlin compiler's output.

**Comment by GraxCode** [comment]
It was the output of eclipse's compiler, so I was expecting it to be OpenJDK 8, guess I'll have to look into it more.

**Comment by Col-E** [comment]
Yup, its been known to generate some notable differences: https://www.benf.org/other/cfr/eclipse-differences.html

**Comment by leibnitz27** [comment]
Ah yes - good - that test causes the same symptoms under ecj8 (and cfr_tests has ecj8 already, yay).

TBH (oh man I hate to say this about ecj/jikes) this is a more sensible compilation, however it doesn't look anything like the string switch pattern, which is why it doesn't get resugared.

As I mentioned though, it *does* look like how kotlin generates string switches, so it's probably fairly easy to tweak the recogniser in that pass.

**Comment by GraxCode** [comment]
Now fails due to ```java
   /*
         * This method has failed to decompile.  When submitting a bug report, please provide this stack trace, and (if you hold appropriate legal rights) the relevant class file.
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchStringRewriter$TooOptimisticMatchException
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchStringRewriter.getString(SwitchStringRewriter.java:402)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchStringRewriter.access$600(SwitchStringRewriter.java:52)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchStringRewriter$SwitchStringMatchResultCollector.collectMatches(SwitchStringRewriter.java:366)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.matchutil.ResetAfterTest.match(ResetAfterTest.java:24)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.matchutil.KleeneN.match(KleeneN.java:24)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.matchutil.MatchSequence.match(MatchSequence.java:26)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.matchutil.ResetAfterTest.match(ResetAfterTest.java:23)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchStringRewriter.rewriteComplex(SwitchStringRewriter.java:200)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchStringRewriter.rewrite(SwitchStringRewriter.java:72)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:841)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:259)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:193)
         * org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:94)
         * org.benf.cfr.reader.entities.Method.analyse(Method.java:521)
         * org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:1035)
         * org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:922)
         * org.benf.cfr.reader.Driver.doClass(Driver.java:83)
         * org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:67)
         * me.nov.threadtear.decompiler.CFRBridge.decompile(CFRBridge.java:80)
         * me.nov.threadtear.swing.panel.DecompilerPanel.update(DecompilerPanel.java:208)
         * me.nov.threadtear.swing.panel.DecompilerPanel.lambda$4(DecompilerPanel.java:166)
         * java.lang.Thread.run(Thread.java:745)
         */
```

**Comment by Marcono1234** [comment]
@GraxCode, for the example jar file you provided with this issue or for a different class? For me the jar file decompiles fine.

**Comment by leibnitz27** [comment]
@GraxCode - as above - have you got an example classfile/jar?  Apples'n'pears are fine.

**Comment by GraxCode** [comment]
Again caused by me being lazy with the API, works now
