### ISSUE TITLE
Attribution in changelog on benf.org is wrong

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#177]
# Description
It appears the attribution in the changelog on https://www.benf.org/other/cfr/index.html is wrong:
> Fix possible infinite loop with infinite signature (thanks marcono1234) 

I assume you are referring to https://github.com/leibnitz27/cfr/commit/cc5ea72770b1b74b9d94ddc3de90f308c5414108, however I did not report that.
Additionally shouldn't it be "with malicious signature"?

**Comment by leibnitz27** [comment]
Hah fair enough
