### ISSUE TITLE
Beyond CFR

### ISSUE THREAD

**Issue by Lanchon** [leibnitz27/cfr#186]
CFR is arguably the best java decompiler. it's also free software, and thank you so much for that. nothing about this project could be better. or could it?

with CFR you've learnt a lot. you started with average knowledge of the Java ecosystem and now you are a top expert in the field. i bet extremely few people understand the intricate corner cases of the platform as well as you do. CFR's success speaks out loud of your smarts, knowledge, perseverance and productiveness. whoever is hiring you should know they are dealing with a superstar; but i guess that took them little time to figure out anyway.

so what's wrong with CFR? your so-called reinventing the wheel has been great for you so far, but now there are diminishing returns. how much more can you learn? or are you working on behalf of your user base now? if the latter is true, then this is the issue with CFR: no matter the effort put into it, CFR can never be what navie people expect or experienced people need.

naive people would expect a cycle of decompilation/edition/recompilation to generate perfect results, but this will never happen. even the simple expectation of translation from bytecode to something readable and guaranteed to be correct goes unfulfilled.

although you can play cat and mouse with javac (et al.) developers and win and decompile perfectly, even trivial bytecode post-processing will always thwart CFR. so what is the practical use if your learning and fun are done?

of course the problem is not CFR; it's Java. Java is unfit for the job.

so my suggestion would go around these lines. retire CFR and try your hand at something different: create a new language, a replacement for Java that provides the required expressiveness and does not get your way. create a decompiler and compiler for it, with guaranteed success and round-trip fidelity. *that's* what people really need.

round-trips should guarantee semantic equivalence (including strange side effects in the face of faults) but not a bit-for-bit clone of the code. IMHO source files should be versioned to allow you freedom in updating the language. of course basic stuff should be relaxed: quoted identifiers, overloading on field types and return types, gotos, code in constructors before object construction, etc, all to the extent accepted by the JVM verifier.

the language should allow compiling against missing libraries, and also decompiling with missing referenced bytecode. this could be done by allowing -think maybe c-style- partial declarations of missing code embedded in the sources of classes using said code. the declarations would contain information that can be obtained by looking only at the consuming bytecode. for instance, source for class X could optionally declare that it's referencing a class C with an int field 'f' and later use that in its code. this would allow the compiler to properly compile X even if source and bytecode for C is not available. btw, the real class C could end up having many fields called 'f' of various types.

the decompiler could choose to always generate full declarations based on usage info, and the compiler could check compatibility against the real thing, if it's there. this would allow compiling only the modded classes if the user so chooses while still verifying binary compatibility with the rest of the code, speeding up the devel cycle of bytecode modding enormously for large apps.

these declarations would be an excellent place to introduce aliases. these would sidestep issues introduced by extreme overloading and help handling obfuscation in general. the decompiler could be configured to produce repeatable, globally unique aliases for names everywhere they are used (eg: for a field it would be: FQN class name + field type + field name), so a code analyst could do a global search and replace on the decompiled source code once she figures out what the name really stands for.

a first shot at it could work on 1.7 bytecode, without knowledge of generics so you don't get bogged down in boring details and concentrate on code. generic info would be preserved though round-trips as obscure annotations at this stage. with versioned source code you could change the language all you want. and for the time being, compilation of old versions would not be required.

you'd no longer struggle against limitations of the JLS or try to shoehorn bytecode you understand into an inadequate language. showstopper would be gone, and i bet if you had invested half the effort on this that you have on CFR, you'd had a finished product by now.

and you'd be reinventing newer wheels: a language and ecosystem. much to learn there, and more fun that the CFR headaches, i guess.

extra notes:

- ASM lib or friends this time around? that wheel is done.
- a look inside R8/D8 to see what they are using for class I/O is also worth the effort IMHO.
- [soot](https://github.com/soot-oss/soot) may be implementing some or much of this stuff. take time to study that codebase too. implementing is fun but extremely expensive; reuse is better.
- if the bytecode backend could be abstracted, this system could eventually be used for dalvik bytecode too which would be invaluable. a subset of the system could be used to translate back and forth between java and dalvik bytecode, which would be another invaluable tool that has been missing for a long time now.
- it would be great if the system could be used to round-trip arbitrary bytecode and then verify that the resulting bytecode is semantically equivalent to the original. this would allow automatic testing of the system against a huge library of proprietary bytecode using the latest obfuscators and their attacks.
- use a global internet-searchable name for the project this time! even if crappy lol. you'll thank yourself for it down the road.

and a final note:

many people simply want to modify a small part/annoying anti-feature of some bytecode. but this system would mostly disallow publishing of mods because they would be intertwined with copyrighted code. your language could be defined to allow not only the definition of bytecode, but also the definition of bytecode modifications. compilation in the latter case would require both, source code defining mods and the original bytecode, in order to generate bytecode. avoid segregating the compilation and patch application steps, as that would encourage the distribution of binary patches, and the world is a better place with all source code in the open.

you can peek at some simple modifications of this sort by looking at the dexpatcher project demo code, but i have better ideas to suggest if you are interested. i'd love for you to obsolete my dexpatcher -and CFR too- with a new tool like this.

**Comment by Lanchon** [comment]
another thing that might be of interest as a starting point an implementation of:
https://en.wikipedia.org/wiki/SafeTSA

but probably soot is better.

**Comment by leibnitz27** [comment]
Oh man, I don't know where to start. ;) 

[ TL;DR - I'm going to close this one as a won't happen ;) - if you want to chat random ideas feel free to email me! ]

ok - thanks - this is very flattering (and you've clearly put a lot of effort in), but .......

..... This is so far from over.  Look at all those open issues.  ;)   I know what you mean, it's a moving target - absolutely.  And if I was trying to sell a solution with guarantees, I'd probably despair.  But fortunately I'm doing it for fun.   (good thing too, this sort of thing will never make you rich and famous ;) ).

..... I absolutely don't know the most about this stuff - not even close - I have a large collection of really shitty heuristics that I've developed that work against my own control flow graph ;)   That's very different from knowing the JVM.   

..... and most of the stuff that's different, weird, and interesting I am still learning by looking at all the crazy (I mean that in a good way) issues that people submit.   (I mean, yeah, it's really a pain to watch the unsolved issue count rising, but hahaha).   

..... We don't need another language ;)  Seriously - there are some great ones out there (and some really terrible ones which have taken over the world[+]).  But I think the use case of people looking to write in a language that can be easily round tripped is *SUPER* small!  Those guys can provide source... [*].   

..... (side note on wheel reimplementation) - sure, it's expensive, sure it's pointless.  And if you're (or I am) doing it in work we probably need to rethink things.  But if you're doing it for fun/education then do it.  The world needs more wheel reimplementors ;)   I sure wouldn't have started this, jad was mostlyGoodEnough ;).   And it's FUN. 

thoughts - There's certainly something in the idea of making patching easy - there are a few tools out there that seem to do a pretty good job (and some of them use CFR tut tut without credit which is very sad [ side note - you know who you are ] ).

Something I've also never seen which sounds pretty cool is 'build me a skeleton for a class which would be sufficient to satisfy the imports/usages in THIS classfile.'.  That would be amusing to build, (and not actually so hard), but totally silly (you wouldn't have implementations of course).   Fun, though!

[+] I don't want to offend by naming names.
[*] I am responsible for at least one language that's still alive.  I get mocked on a daily basis.  LOL.

**Comment by Lanchon** [comment]
morning! well it was worth a try... thanks for taking the time to respond!

**Comment by Col-E** [comment]
> and some of them use CFR tut tut without credit

😢 

What is your preferred form of credit? Including a small aside in the readme may help counter this.

**Comment by leibnitz27** [comment]
> What is your preferred form of credit? Including a small aside in the readme may help counter this.

You make a good point.  I've certainly seen a few places where CFR's not mentioned on the website, credits, or docs, and the header comment is stripped away in generated code.   That makes me sad.
I'll tweak the readme.

> Like this? https://github.com/gbalats/jphantom

Awesome.    Totally freaking pointless, I *LOVE* it ;)  Thanks for pointing that out!!

**Comment by Lanchon** [comment]
my dexpatcher is used by my haystack. haystack is a replacement for needle, somewhat brittle solution to inject signature spoofing to binary android OSes (required to replace google services with free ones).

i made haystack as a trivial example of how to use dexpatcher, but it has seen more use than dxp :)

anyway, someone came and took haystack and dxp (all is GPL) as they are, renamed them, made a wrapper that invokes them directly on the android device without command line (its all pure java) and published with no mention of the other projects whatsoever.

and of course its the distro that gets 99% of the usage lol.

its legal, GPL allows it. he was invoking my stuff suboptimally so i helped the guy by suggesting some small changes (enabling multithreded patching, applying several patches in one pass) that sped up gis distro 10+ times. still no credits :) i usually inform him of new releases anyway, but he s not always diligent at repackaging.

everything is legal so its fine, happens :)

funny how people ask me from time to time why do i maintain haystack if theres a simpler better option. i have to let then know that the simpler better option is in fact pristine virgin haystack lol.

and ive another story...

**Comment by Lanchon** [comment]
i created a safe data retaining phone repartitioning tool (https://github.com/Lanchon/REPIT) that later was ported to tens of devices, because some popular device at the time suddenly required it urgently. and i published an 0.1 version in a couple if days to assist people in need.

then some people alerted me that someone was live-stealing my releases, removing the license and copyright info, adding themselves as the author, rewinding publishing dates by a day or two and publishing elsewhere. very funny lol.

then something happened that caused me to leave XDA and move all my projects to gitgub:

https://github.com/Lanchon/REPIT/blob/master/README-CHEF-KOCH.md

and then the thief contacted me:

https://github.com/Lanchon/REPIT/issues/37

and then more people contacted me lol:

https://github.com/Lanchon/REPIT/issues/89
https://github.com/Lanchon/REPIT/issues/105

so there... it can always be worse :)

as long as copyright and license are respected, you should be happy about people using your code. proper creditting is a test of character.
