### ISSUE TITLE
What is the license of this repo?

### ISSUE THREAD

**Issue by KOLANICH** [leibnitz27/cfr#19]

**Comment by Col-E** [comment]
http://www.benf.org/other/cfr/license.html - MIT

**Comment by KOLANICH** [comment]
I guess a `LICENSE` file should be created in the repo root.

**Comment by ItzSomebody** [comment]
https://github.com/leibnitz27/cfr/blob/master/src/license.txt

**Comment by Col-E** [comment]
Could be _copied_ to the root. I imagine its in the `src` folder so it's included in the build process.

**Comment by leibnitz27** [comment]
Yup, as @Col-E says.   Duplicated in root.
(MIT being the standard, 'hey, don't be an asshole and pass this off' license. )
