### ISSUE TITLE
Incorrect for loop decompilation

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#192]
# CFR version
a913e06

# Compiler
JDK 14, or what ever special compiler IntelliJ uses

# Description
The code doesn't produce the same result after decompilation:
```java
 public static void main(String[] args) {
    int n = 15;
    for (float i = 0; i < n; i++, i*= 2, System.out.println(i), i -= 2, i *= 1.2, i += 0.5) {
    }
  }
```
prints
```java
2.0
3.0
5.4
11.16
24.984
```
Decompiled code:
```java
    public static void main(String[] args) {
        int n = 15;
        for (float i = 0.0f; i < (float)n; i -= 2.0f) {
            i += 1.0f;
            System.out.println(i *= 2.0f);
            i = (float)((double)i * 1.2);
            i = (float)((double)i + 0.5);
        }
    }
```
prints
```java
2.0
3.8000002
8.120001
18.488003
```
Edit: Not an IDE bug

**Comment by GraxCode** [comment]
Affected class:
[ArrayIter.class.txt](https://github.com/leibnitz27/cfr/files/4825935/ArrayIter.class.txt)
Seems like with other compilers this problem does not occur. This one works fine:
[WeirdForLoop.class.txt](https://github.com/leibnitz27/cfr/files/4825941/WeirdForLoop.class.txt) (ECJ)

**Comment by leibnitz27** [comment]
Yes, it's a decompiler issue.  I can't speak for the others, as CFR shares 0 heritage with them, but what's happening for me is that the accounting on the -2 mutation is wrong, at a guess.   

Good spot.

**Comment by GraxCode** [comment]
Yeah. CFR seems to take the -= 2 and put it into the for loop definition, although it's isnt at the end of the code.

**Comment by leibnitz27** [comment]
A simpler test

https://github.com/leibnitz27/cfr_tests/blob/master/src_6/org/benf/cfr/tests/LoopTest74.java

**Comment by leibnitz27** [comment]
It's the difference between the * and the - looking like (due to the double casts) they can be treated as mutations or not that does it.  (slightly different accounting paths.)

Fun one, will try to get to that soonish.
