### ISSUE TITLE
Dont downcast objects

### ISSUE THREAD

**Issue by cookiedragon234** [leibnitz27/cfr#203]
# Problem solved by this feature
The following code will produce the following output:
```
getstatic("java/lang/System", "out", "Ljava/io/PrintStream;")
ldc("Test")
invokevirtual("java/io/PrintStream", "println", "(Ljava/lang/Object;)V")
```
```Java
System.out.println((Object)"Test");
```

# Feature description
It should be recognised that java/lang/String is a child of java/lang/Object and therefore does not need to be casted

# Considerations
Runtime classes must be scanned to do this check, either using reflection or loading them from file system

# Alternatives
None

**Comment by Lanchon** [comment]
CFR knows that. the problem is that println may have a println(String) version but your code is calling the println(Object) version, so the cast is needed so that the Java text expresses what the bytecode does.

i believe CFR can look at the defininition(s) of println and avoid the cast if unnecessary, but you have to feed it the definitions in the command line. does CFR complain that i cant find certain classes in a coment at the beginning of the decompilation? well, then "you're doing it wrong".

**Comment by cookiedragon234** [comment]
I am using latest CFR and it is not complaining about not finding classes, I've provided it a full classpath.

And yes, I see your point about the overloaded methods, specifying the Object cast is necessary.

**Comment by Lanchon** [comment]
if CFR has access to the definitions of println and they do not provide any println(T) where T is not Object and String is assignable to T, then CFR could do a better job: reopen this and have the dev take a look.

**Comment by leibnitz27** [comment]
Indeed - this is just the difference between 

```
  public void foo();
    Code:
       0: ldc           #2                  // String Hello chaps
       2: astore_1
       3: getstatic     #3                  // Field java/lang/System.out:Ljava/io/PrintStream;
       6: aload_1
       7: invokevirtual #4                  // Method java/io/PrintStream.println:(Ljava/lang/String;)V
      10: getstatic     #3                  // Field java/lang/System.out:Ljava/io/PrintStream;
      13: aload_1
      14: invokevirtual #5                  // Method java/io/PrintStream.println:(Ljava/lang/Object;)V
      17: return
```

where two different methods are called, and casts are added as necessary.

```
/*
 * Decompiled with CFR 0.151-SNAPSHOT (f27757b-dirty).
 */
package org.benf.cfr.tests;

public class CastTest26 {
    public void foo() {
        String s = "Hello chaps";
        System.out.println(s);
        System.out.println((Object)s);
    }
}
```
