### ISSUE TITLE
Existing classes in the classpath overshadows the input class

### ISSUE THREAD

**Issue by andylizi** [leibnitz27/cfr#206]
## CFR version
`0.151-SNAPSHOT` (f4eca68-dirty)

## Compiler
javac `1.8.0_221`

#### Steps to reproduce
1. Compile the following source file (or download the sample from below)
```java
package java.lang;
public class Exception {
    public void foo() {
        System.out.println("My modified JDK class :D");
    }
}
```
2. Rename the output class `Exception.class` to something like `a.class`
3. `java -jar cfr.jar a.class`

#### Expected output
```java
/*
 * Decompiled with CFR 0.151-SNAPSHOT (f4eca68-dirty).
 */
package java.lang;

public class Exception {
    public void foo() {
        System.out.println("My modified JDK class :D");
    }
}
```

#### Actual output
```java
/*
 * Decompiled with CFR 0.151-SNAPSHOT (f4eca68-dirty).
 */
package java.lang;

public class Exception
extends Throwable {
    static final long serialVersionUID = -3387516993124229948L;

    public Exception() {
    }

    public Exception(String string) {
        super(string);
    }
// ...
// basically the 'original' java.lang.Exception class
// https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/default/src/share/classes/java/lang/Exception.java
```

#### Note
This only happens when the same class name exists in classpath and the name of the class file doesn't match.

## Example
[a.class.txt](https://github.com/leibnitz27/cfr/files/5140416/a.class.txt)

**Comment by leibnitz27** [comment]
Nice!  Oops.

**Comment by Lanchon** [comment]
can CFR be configured to ignore the runtime classpath? this is important for some use cases.

**Comment by leibnitz27** [comment]
There's an interesting follow up here - I 'support' illegally named files as the reload fails, so we just go on with what we have.

However, 

> can CFR be configured to ignore the runtime classpath? this is important for some use cases.

@Lanchon - No - doesn't seem unreasonable, though of course you'll miss out on useful generics from collections etc.  Out of interest, what's a specific use case? (other than "I don't want class path" :) ).   Never really noticed that to be a problem.

**Comment by Lanchon** [comment]
> what's a specific use case?

using a different boot classpath, such as the android runtime. or a different version of the JRE. or some classpath of an embedded VM. etc...
