### ISSUE TITLE
Decompilation of boolean expressions with varargs method invocations fails

### ISSUE THREAD

**Issue by nitram84** [leibnitz27/cfr#217]
# CFR version

CFR 0.151-SNAPSHOT (b79446a) and CFR 0.150, so this is not a regression of recent changes

# Compiler

openjdk8, openjdk11

# Description

Decompilation of boolean expressions with varargs method invocations fails in some cases:

# Example

```java
public class CfrTest1 {

  private static boolean isValid(String... string) {
    return false;
  }

  protected static boolean b1;
  protected static final boolean isValid = b1 && isValid("test");
}
```

Second example:

```java
public class CfrTest2 {

  public static boolean c(String... values) {
    return false;
  }

  public boolean isValid(int x) {
    return false;
  }

  protected int broken(int x) {
    int i = 0;
    boolean a = isValid(x) && c("test");
    boolean b = isValid(x + 1);

    if (a) {
      i = 0;
    } else if (b) {
      i = 1;
    }
    return i;
  }
}
```

These samples may be used as test cases for the cfr test suite.

**Comment by Marcono1234** [comment]
Could you please fix the formatting of your example code? You have to use three backticks for code blocks, e.g.:
<pre>
```java
class MyClass {
    ...
}
```
</pre>

**Comment by nitram84** [comment]
@Marcono1234 Thank you!

**Comment by leibnitz27** [comment]
Nice, thanks.
