### ISSUE TITLE
Decompiling while-true loop fails

### ISSUE THREAD

**Issue by nitram84** [leibnitz27/cfr#220]
# CFR version

CFR 0.151-SNAPSHOT (bc71426) and CFR 0.150, so this is not a regression of recent changes

# Compiler

openjdk8, openjdk11

# Description

Decompiling the following loop fails:

# Example

```java
public class CfrTest1 {
  private int i;

  public int doSomething() {
    while (true) {
      if (i <= 1) {
        doSomething2();
        if (i == 0) {
          break;
        }
      }

      if (i >= 41) {
        doSomething2();
        if (i == 42) {
          return 1;
        }
      }
    }
    return 0;
  }

  private void doSomething2() {
  }
}
```

This example can be used for the cfr test suite.

**Comment by leibnitz27** [comment]
Thanks.  Annoyingly (or amusingly, natch), it's possible to get this right without lifting returns to the jump site, so the default decompilation looks a little weird with the labelled block.

Might consider lifting jumps always if they only have one source....
