### ISSUE TITLE
Failed to decompile nested conditions

### ISSUE THREAD

**Issue by nitram84** [leibnitz27/cfr#222]
# CFR version

CFR 0.151-SNAPSHOT (dfdb9d5) and CFR 0.150, so this is not a regression of recent changes

# Compiler

openjdk8, openjdk11

# Description

Nested conditions could not be decompiled in some cases:

# Example

```java
public class CFRTest1 {

  public int checkConditions(boolean a, boolean b, boolean c) {
    if (a) {
      if (b) {
        doSomething();
      } else {
        if (c) {
          doSomething();
          return 1;
        } else {
          doSomething();
          return 0;
        }
      }
    } else {
      doSomething();
    }
    doSomething();
    return 2;
  }

  private void doSomething() {
  }
}
```

This example can be used for the cfr test suite.

**Comment by leibnitz27** [comment]
Hm - the fix is clean enough but does highlight that (hah, like your last issue) I can be a bit keen to use anonymous blocks.   I think a few more transforms to reduce these, when I get a chance \o/
