### ISSUE TITLE
package-info imports are printed in wrong location

### ISSUE THREAD

**Issue by Col-E** [leibnitz27/cfr#223]
# CFR 150 release (1361cd7fa74f25f30a6bbf72c825d83647d2cdaf)

# Compiler
Javac 1.8.0_252

# Description
For `package-info` the `imports` come before the `package` statement, and this is not proper. 
I find putting modifying annotations at the top of the file to be weird, but I guess that does technically match the specs.

# Example
CFR decompiles `package-info` like the following:
```java
import org.osgi.annotation.versioning.Version;

@Version(value="2.3.4")
package org.apache.sling.api;
```

However, compiling this will fail. Move the import statement down below the package defintion.
```java
@Version(value="2.3.4")
package org.apache.sling.api;

import org.osgi.annotation.versioning.Version;
```
Now it compiles.

**Comment by leibnitz27** [comment]
Oops!  Thanks.
