### ISSUE TITLE
CFR fails when I try to decompile class file of a kotlin function which uses Sequence.

### ISSUE THREAD

**Issue by cpdyj** [leibnitz27/cfr#225]
# CFR version
cfr-0.150
`java -jar cfr-0.150.jar Lexer.class`

# Compiler

```
kotlin("jvm") version "1.4.21"
javac 11.0.9.1
```

# Description

`org.benf.cfr.reader.util.ConfusedCFRException: Extractable last case doesn't follow previous, and can't clone.`

# Example

[decompileResule.txt](https://github.com/leibnitz27/cfr/files/5756323/compileResule.txt)
[queryhelper-compiled-classes.zip](https://github.com/leibnitz27/cfr/files/5756326/queryhelper-compiled-classes.zip)
[all-source.zip](https://github.com/leibnitz27/cfr/files/5756328/all-source.zip)

Thanks for your explaining.

**Comment by leibnitz27** [comment]
Interesting - this looks like Kotlin's coroutine support producing some pretty funky bytecode (two switches which interleave and fall into each other).   

In this case, we actually recover pretty well (I mean, it produces reasonably correct pseudo code, it's kotlin, we're unlikely to recover *perfect* java....) if we allow a recovery pass to selectively ignore this.
