### ISSUE TITLE
ConfusedCFRException: Expecting a ConstantPoolEntryLiteral or ConstantPoolEntryDynamicInfo

### ISSUE THREAD

**Issue by FrankVanHam** [leibnitz27/cfr#226]
# CFR version
CFR 0.150

# Compiler
javac 11.0.2

# Java version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

# Description
The decompiler fails to decompile the attached jar file. The jar file is generated from another JVM language, so i do not have the source java file.

# Example
output and jar file is attacked.
[decompiler_output.txt](https://github.com/leibnitz27/cfr/files/5792581/decompiler_output.txt)
[jar_decompiler_lp.decompile_target.1.jar.txt](https://github.com/leibnitz27/cfr/files/5792582/jar_decompiler_lp.decompile_target.1.jar.txt)

**Comment by leibnitz27** [comment]
Hey - this works fine with the tip of master.

I guess I need to start thinking about another release ;)
