### ISSUE TITLE
Help finding option to match overloaded methods

### ISSUE THREAD

**Issue by MikeAndrson** [leibnitz27/cfr#227]
I can decompile a certain method body using `--methodname` argument with CFR. like:

`/storage/emulated/0/cfr150/SrcCodeEditor.class --methodname onBackPressed --outputdir /storage/emulated/0/cfr150/out`

but this argument only allows method names, and not full method signatures. This leads to some problems with overloaded methods. How can I match an overloaded method using this argument? CFR throws IllegalStateException with "no such method" if I use a full method signature such as `myMethod(Ljava/lang/String;)V`

**Comment by leibnitz27** [comment]
Hi - this isn't currently supported but I don't see any reason not to add the facility, wouldn't be too tricky.
That being said, if you're using CFR through the API, you could do this yourself fairly easily - seems like an odd use case for the command line - are you embedding this?

**Comment by HeyStudiosDEV** [comment]
@leibnitz27 ,

I recently started making a small reverse engineering project in my free times for decompiling Android APKs. I use dex2jar then run CFR on the output jar. I haven't checked the API yet though, was just playing around with the command line a little bit to see if I actually need to write a wrapper around the API or if `org.benf.cfr.reader.Main.main(args);` was sufficient. Guess not, I might need to start utilizing the API. Still, being able to do it using command line would be cool.

Thanks for the reply 👍
