### ISSUE TITLE
Cannot decompile Scala standard library, crashes

### ISSUE THREAD

**Issue by KOLANICH** [leibnitz27/cfr#23]
https://downloads.lightbend.com/scala/2.13.0/scala-2.13.0.zip

```
java -jar cfr-0.146.jar ./scala-2.13.0\lib\scala-library.jar --outputdir ./ --extraclasspath ".\scala-2.13.0\lib\scala-reflect.jar;%JAVA_HOME%\lib\rt.jar"
```
decompiles some classes, but crashes somewhen.

Krakatau is succesful (though it has some limitations).

**Comment by leibnitz27** [comment]
Interesting - a (what I would term in javac-produced code) 'intermediate' lambda expression was recursive, and hence CFR was trying to inline it.  

I don't think it's possible to get javac to do that.
