### ISSUE TITLE
Non-static [ externally referenced] constants

### ISSUE THREAD

**Issue by Kyuuhachi** [leibnitz27/cfr#237]
CFR version 0.151, javac version 1.8.0_282

When getting a non-static constant field from a non-constant expression, javac inserts a null check (`.getClass()`) on the expression, then substitutes the constant value. CFR currently usually decompiles this into a couple of temp variables and includes the `.getClass()` statement in the result. While this does give a correct program, it greatly hinders readability, and doesn't show *which* constant comes from the expression, which makes manual cleanup much harder.

As with other constants, there's no ideal way to decompile it. A first thought would be to check all constants in the target class, but that breaks apart if there are multiple sets of integer-valued constants, or if the constant value is modified by constant folding (though constant folding doesn't seem to actually happen here, only type conversions).

My suggestion would be to decompile it into `CFR_CONSTANT_FIELD(a, 8)`, or `a.CFR_CONSTANT_FIELD(8)`, or something similar. It's ugly, but it doesn't break the expression flow, and shows clearly which constant is derived from the expression. Of course, referencing an undefined function is a problem by itself...

[This](http://hg.openjdk.java.net/jdk8/jdk8/langtools/file/1ff9d5118aae/src/share/classes/com/sun/tools/javac/jvm/Gen.java#l2406) is the relevant part of javac.

# Example
```java
class Test1 {
	final int eight = 8;
}

class Test1s {
	int test1a(Test1 a) {
		return a.eight;
	}

	double test1b(Test1 a) {
		return a.eight * 2.5 + Math.sin(a.eight+1) * 8;
	}
}
```
Decompiles into
```java
class Test1s {
    Test1s() {
    }

    int test1a(Test1 test1) {
        test1.getClass();
        return 8;
    }

    double test1b(Test1 test1) {
        test1.getClass();
        test1.getClass();
        return 8.0 * 2.5 + Math.sin(8 + 1) * 8.0;
    }
}
```
No way to tell that the third `8.0` is the one that was not loaded from a constant. One can tell that something weird is going on with the middle one since it isn't constant folded, but that's not possible in general. The proposed output would be something like 
```java
class Test1s {
    Test1s() {
    }

    int test1a(Test1 test1) {
        return CFR_CONSTANT_FIELD(test1, 8);
    }

    double test1b(Test1 test1) {
        return CFR_CONSTANT_FIELD(test1, 8.0) * 2.5 + Math.sin(CFR_CONSTANT_FIELD(test1, 8) + 1) * 8.0;
        // Alternatively
        return test1.CFR_CONSTANT_FIELD(8.0) * 2.5 + Math.sin(test1.CFR_CONSTANT_FIELD(8) + 1) * 8.0;
    }
}
```
Sure, the line gets quite long, but I find it a lot clearer nonetheless.

**Comment by leibnitz27** [comment]
Super slow working through stuff atm.....

It's tempting to restore the original - rather than keeping the extracted constants.   I do something similar for static strings (but don't even try for numerics, because it's reasonably likely that a string literal is a valid relink to a constant, but not an integer) - but like you say, here, we've got a decent hint it was a constant....

This actually works out quite nicely... (assuming unambiguous constants)


```
public class FieldTest237a {
    public final int x = 9;
    public final int y = 10;
    public static final int z = 10;
    public final String f = "foo";

    public int x1() { return x;}
    public String f1() { return f;}
}

public class FieldTest237c {
    int foo(FieldTest237a a) {
       return a.z + 2 < a.x ? a.x : a.y;
    }

    String foo2(FieldTest237a a) {
        return a.f;
    }
}
```

Without a available:

```
/* Could not load the following classes:
 *  org.benf.cfr.tests.FieldTest237a
 */
package org.benf.cfr.tests;

import org.benf.cfr.tests.FieldTest237a;

public class FieldTest237c {
    int foo(FieldTest237a a) {
        int n;
        a.getClass();
        if (9 < 10) {
            a.getClass();
            n = 9;
        } else {
            a.getClass();
            n = 10;
        }
        return n;
    }

    String foo2(FieldTest237a a) {
        a.getClass();
        return "foo";
    }
}
```

With a available

```
import org.benf.cfr.tests.FieldTest237a;

public class FieldTest237c {
    int foo(FieldTest237a a) {
        return 10 + 2 < a.x ? a.x : a.y;
    }

    String foo2(FieldTest237a a) {
        return a.f;
    }
}
```

**Comment by leibnitz27** [comment]
(not on master yet)
