### ISSUE TITLE
Some code which confuses CFR

### ISSUE THREAD

**Issue by tmoonkey** [leibnitz27/cfr#245]
I am generating some custom bytecode, and it confuses CFR. I understand that this may not be very interesting since it's not Java (or any other language used by anyone for that matter), but just in case, attached is an example. Here CFR mixes up `locals` and `module`, which are local vars at indexes 2 and 3 respectively. The code does things with `locals`, but CFR displays access to `module` instead. Here's what I see:
```
    protected IPyObj __call__(PyUFuncFrame frame) {
        void module;
        PyCell[] locals = frame.locals;
        PyUModule pyUModule = this.module;
        if (PyFuncHandler.callFunc((IPyObj)pyUModule.getAttr((String)"type"), (IPyObj)module[0].v((boolean)true)).equals((Object)PyFuncHandler.callFunc((IPyObj)pyUModule.getAttr((String)"type"), (IPyObj)PyStr.ucs2((String)"")))) {
            return PyFuncHandler.callFunc((IPyObj)pyUModule.getAttr((String)"ord"), (IPyObj)module[0].v((boolean)true));
        }
        return module[0].v((boolean)true);
    }
```
No idea where that `void module` in the beginning comes from. `locals` is correct, and `pyUModule` is what should `module` be.

**Comment by tmoonkey** [comment]
Class file: [f$_ctoi.zip](https://github.com/leibnitz27/cfr/files/6360351/f._ctoi.zip)
CFR output: [cfr.txt](https://github.com/leibnitz27/cfr/files/6360367/cfr.txt)

**Comment by leibnitz27** [comment]
Looks like there's something odd with the name table (haven't really dug) - There's no need for it to be correct, but it's (basically) the only untrustworthy thing I try to use, as people expect matching names where possible.....

Try using '--usenametable false'

I should probably add that as a hint to the 'void declaration' warning, as it's a common symptom.

```
public final class f$_ctoi
extends PyUFunc {
    protected IPyObj __call__(PyUFuncFrame pyUFuncFrame) {
        PyCell[] pyCellArray = pyUFuncFrame.locals;
        PyUModule pyUModule = this.module;
        if (PyFuncHandler.callFunc((IPyObj)pyUModule.getAttr("type"), (IPyObj)pyCellArray[0].v(true)).equals(PyFuncHandler.callFunc((IPyObj)pyUModule.getAttr("type"), (IPyObj)PyStr.ucs2((String)"")))) {
            return PyFuncHandler.callFunc((IPyObj)pyUModule.getAttr("ord"), (IPyObj)pyCellArray[0].v(true));
        }
        return pyCellArray[0].v(true);
    }

    public f$_ctoi(PyUModule pyUModule, IPyObj[] iPyObjArray, PyCell[] pyCellArray) {
        super(pyUModule, "_ctoi", null, FuncSig.make((String[])new String[]{"c"}, (ParamKind[])new ParamKind[]{ParamKind.POS_OR_KW}), iPyObjArray, pyCellArray, new String[]{"c"});
    }
}
```

**Comment by leibnitz27** [comment]
Closing as answered... (unless it isn't ;) )

**Comment by leibnitz27** [comment]
Closing as answered... (unless it isn't ;) )

**Comment by tmoonkey** [comment]
Indeed, the table was messed up, I used wrong index for one of the variables. After I fixed that, cfr shows the right stuff. It's awesome because intellij can't decompile this code, while cfr groks it. Thanks!
