### ISSUE TITLE
CFR hangs infinitely when trying to decompile a class with empty infinite loop.

### ISSUE THREAD

**Issue by SuperCoder7979** [leibnitz27/cfr#261]
# CFR version
0.151

# Compiler
Javac 1.8.0_275

# Description
CFR hangs infinitely when trying to decompile a [class with empty infinite loops.](https://github.com/QuiltMC/quiltflower/blob/fix/empty-infinite-loops/testData/src/pkg/TestInfiniteLoop.java) Unfortunately, I've gotten into the bad habit of putting multiple decompiler test cases into the same class so I'm not sure which method causes it to break exactly 😅 Fun aside: Fernflower refused to decompile those first 4 methods at all before I patched it, as it removed redundant gotos and failed hard when it tried to stick a null statement into the method. I figured that I'd test CFR on it to see what it would do to compare, and here we are 😛

# Example
Here's the [source code](https://github.com/QuiltMC/quiltflower/blob/fix/empty-infinite-loops/testData/src/pkg/TestInfiniteLoop.java) and the [class file.](https://github.com/QuiltMC/quiltflower/blob/fix/empty-infinite-loops/testData/classes/pkg/TestInfiniteLoop.class)

**Comment by leibnitz27** [comment]
Can't be having that ;) fortunately a pretty obvious one - cheers.
