### ISSUE TITLE
Decompiling with --obfuscationpath creates incorrect package declaration and import

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#27]
# CFR version
0.147

# The bug
When decompiling with the newly introduced `--obfuscationpath` option, the `package` declaration in the Java source uses the obfuscated package name, and additionally the current class is added as import.

For example when decompiling `a.a` (deobf: `test.Main`) the created source is:
```
package a;

import test.Main;

class Main {
    ...
}
```

instead of

```
package test;

class Main {
    ...
}
```

# Reproduction steps
1. Download
    - [cfr-mapping-test-obf.jar.zip](https://github.com/leibnitz27/cfr/files/3756191/cfr-mapping-test-obf.jar.zip) (remove `.zip`, this is only to make GitHub happy)
    - [mappings.txt](https://github.com/leibnitz27/cfr/files/3756180/mappings.txt)
2. Run CFR
    ```
    java -jar ./cfr-0.147.jar cfr-mapping-test-obf.jar --obfuscationpath mappings.txt
    ```

**Comment by Marcono1234** [comment]
Thanks for fixing this and the other issues so fast!

Though it appears the following line still causes issues when the obfuscated class is in the default package (= no package name):
https://github.com/leibnitz27/cfr/blob/ea61d56dfb7b1d0fa0dac820f118f0f7281f0084/src/org/benf/cfr/reader/entities/classfilehelpers/AbstractClassFileDumper.java#L73

Then the mapped package name will not be used.

**Comment by leibnitz27** [comment]
Nice.  I haven't got around to actually using proguard yet, so don't have a test case for that, but the fix was reasonably obvious.   

Thanks for the excellent bug reports.
