### ISSUE TITLE
MatchIterator throws "ArrayIndexOutOfBoundsException  and the code is not robust

### ISSUE THREAD

**Issue by chenggwang** [leibnitz27/cfr#270]
# CFR Version
0.152-SNAPSHOT (44bddad)
# Compiler
OpenJDK jdk-16.0.2
# Description
1. **_ArrayIndexOutOfBoundsException for the toString () method of Matchiterator_**:
IDEA in Debug mode,Variable'view will call toString(),but this time idx==-1,
so this method"toString()" will  throw ArrayIndexOutOfBoundsException.When the advance() method 
has not been called,the idx has always been -1.
2. **_NullPointerException for the Matchiterator's hasnext(), isfinished() method_**:
The data.size() method will throw NullPointerException,Although in the current code, 
this problem will not be raised,because the constructor parameter(List data) of MatchIterator is 'ListFactory.newList()',
So so far, The data of MatchIterator won't be null.But other places use this class Matchiterator,Inevitably, 
it will not cause NullPointerException.In terms of code robustness,data!=null is necessary

# Example
``` java
//src/org/benf/cfr/reader/bytecode/analysis/opgraph/op4rewriters/SwitchStringRewriter.java
//Line:#137
private void rewriteComplex(List<StructuredStatement> structuredStatements) {
        // Rather than have a non-greedy kleene star at the start, we cheat and scan for valid start points.
        // switch OB (case OB (if-testalternativevalid OB assign break CB)* if-notvalid break assign break CB)+ CB
        MatchIterator<StructuredStatement> mi = new MatchIterator<StructuredStatement>(structuredStatements);
```
<img width="944" alt="error" src="https://user-images.githubusercontent.com/90715678/133878624-78cd6996-cfe7-4974-a24c-8f4bec0e4aed.png">

``` java
//src/org/benf/cfr/reader/bytecode/analysis/opgraph/op4rewriters/matchutil/MatchIterator.java
public class MatchIterator<T> {
    private final List<T> data;
    private int idx;

    public MatchIterator(List<T> data) {
        this.data = data;
        this.idx = -1;
    }
	
	public boolean hasNext() {
        return idx < data.size() - 1;
		}
    private boolean isFinished() {
        return idx >= data.size();
	}

    private MatchIterator(List<T> data, int idx) {
        this.data = data;
        this.idx = idx;
    }
    public String toString() {
        if (isFinished()) return "Finished";
        T t = data.get(idx);
        return t == null ? "null" : t.toString();
	}
}
```

**Comment by leibnitz27** [comment]
As per comment on PR - I'm going to revert the null protection here - I'd rather it blew up noisly than silently failed.
(actually, worse, if it was null isFinished would never work here, so possible infinite loop)

**Comment by leibnitz27** [comment]
Have also restricted the size of the dump - this is potentially used on massive data, so walking it all is pointless. (esp since you're in the debugger here!)
