### ISSUE TITLE
Enums are decompiled as classes which extend Enum

### ISSUE THREAD

**Issue by DalekCraft2** [leibnitz27/cfr#276]
# CFR version

0.151

# Compiler

javac 17.0.1

# Description

Enum classes are decompiled as classes which extend `Enum`, and all of their values are replaced with constants. They also get synthetic methods which conflict with the automatic enum methods and cause errors, as well as a constant for the values.
I tested with records, annotations, and `package-info.java`, and nothing weird happened with them.

# Example

[TestEnum (source).txt](https://github.com/leibnitz27/cfr/files/7637900/TestEnum.source.txt)
[TestEnum (decompiled).txt](https://github.com/leibnitz27/cfr/files/7637901/TestEnum.decompiled.txt)

**Comment by leibnitz27** [comment]
Enums have resugaring correctly for several years....
(They're tested fairly heavily in https://github.com/leibnitz27/cfr_tests/tree/master/src_6/org/benf/cfr/tests , and indeed this example works fine for me. )

Can you provide a specific class file?   (attach renamed to txt, zip and rename if it still complains).

The most likely thing is you're using eclipse/jikes, which frequently (ish) changes its enum representation. 

```
java -jar c:\Downloads\cfr-0.151.jar java.sql.PseudoColumnUsage
/*
 * Decompiled with CFR 0.151.
 */
package java.sql;

public enum PseudoColumnUsage {
    SELECT_LIST_ONLY,
    WHERE_CLAUSE_ONLY,
    NO_USAGE_RESTRICTIONS,
    USAGE_UNKNOWN;

}```

**Comment by DalekCraft2** [comment]
I am using IntelliJ IDEA, and I already attached an example.

**Comment by leibnitz27** [comment]
I meant the class file; but I see your issue anyway - hadn't spotted that you're not using master.

Enums changed their representation a while back;  this has been fixed (on master) more or less since it happened.

I guess I need to do another release....

**Comment by leibnitz27** [comment]
Right - that was the excuse I needed to finally release again.   0.152 should fix your woes.
