### ISSUE TITLE
bytecode location question

### ISSUE THREAD

**Issue by GG22G2** [leibnitz27/cfr#303]
As in the lower right corner of my figure, the 26 lines of the java file correspond to the fifth byte of the bytecode, but decompiled with javap, the fifth byte is dup, and the second byte is new.

![VHRU5XJWZRIRGSQO{4BEL_6](https://user-images.githubusercontent.com/31408730/163679766-783690a0-6efc-4b25-b512-0227d5b560da.png)

**Comment by leibnitz27** [comment]
Hopefully more or less answered by http://www.benf.org/other/cfr/line_numbers.html
