### ISSUE TITLE
Is there a similar method to analyze(List<String>) that returns a String instead of void?

### ISSUE THREAD

**Issue by Andreas-White** [leibnitz27/cfr#318]
Hello great work! I want get the context of a .class file as String in order to traverse it and display specific methods from the source file to the user. Is there such capability?

**Comment by leibnitz27** [comment]
You can sink into a string like this https://github.com/leibnitz27/cfr_client/blob/master/src/org/benf/cfr_client_example/WithSink.java

Sorry - there isn't a handy 'split up into methods' sink right now.

**Comment by Andreas-White** [comment]
Thank you for the response! That's fine what you provided works for me too.
