### ISSUE TITLE
Decompile to zip to prevent long file names problem

### ISSUE THREAD

**Issue by Kazbek** [leibnitz27/cfr#321]
Is it possible to decompile to a zip archive? On Windows, the problem is with long file names, and it is difficult to understand from the summary file in which folder the file was renamed.

**Comment by Marcono1234** [comment]
Are you calling CFR from code or are you executing it from command line? If you are calling it from code, then you could probably use the [CFR API](https://www.benf.org/other/cfr/api/) to create the ZIP file yourself.

**Comment by Kazbek** [comment]
Unfortunately I use it from command line.
