### ISSUE TITLE
Decompiling with --obfuscationpath writes nested classes as separate source files

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#33]
# CFR version
0.147

# Description
When decompiling with the newly introduced `--obfuscationpath` option, nested classes are created as separate source files producing invalid Java code.
```
import mypackage.MyClass;

// Constains a period (`.`), not a valid class name
public class MyClass.Nested {
}
```

# Reproduction steps
1. Download
    - [nested-obf.jar.zip](https://github.com/leibnitz27/cfr/files/3758147/nested-obf.jar.zip) (remove `.zip`, this is only to make GitHub happy)
    - [mappings.txt](https://github.com/leibnitz27/cfr/files/3758154/mappings.txt)

2. Run CFR
    ```
    java -jar ./cfr-0.147.jar nested-obf.jar --obfuscationpath mappings.txt
    ```

**Comment by Marcono1234** [comment]
@leibnitz27, it appears the fix does not work for the attached `.jar` file. However, I have seen that it works correctly for other class files (which I cannot share).

**Comment by leibnitz27** [comment]
Ah!  It works when considering the *class* on its own, which I tend to do.  But not the jar.

Good spot.
