### ISSUE TITLE
Decompiling specific package(s)

### ISSUE THREAD

**Issue by drori200** [leibnitz27/cfr#336]
As the title says, is it possible to decompile specific package(s) with CFR?
Currently I have a jar that fails to be decompiled with my decompiler of choice (QuiltFlower) due to two package. Because of that, I have to mix the usage of CFR and QF to get the desired decompiled code.

**Comment by leibnitz27** [comment]
You can just do this with --jarfilter REGEX

i.e.

java -jar cfr.jar cfr.jar --jarfilter "org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.checker.*"

**Comment by leibnitz27** [comment]
it's just a regex.  So use a disjunction.

java -jar cfr.jar cfr.jar --jarfilter "^(com.example.app|net.example.code)"
