### ISSUE TITLE
having an issue with the error "Error: Could not find or load main class cfr-0.152.jar"

### ISSUE THREAD

**Issue by krispyking24** [leibnitz27/cfr#358]
heres the command im running in a cmd window opened in the folder CFR is in, I don't have the license to better pvp so I'm not going to upload it. in short what am I doing wrong
java cfr-0.152.jar C:\Users\user\AppData\Roaming\PrismLauncher\instances\Adrenaline(1.21)\.minecraft\mods\BetterPvP_24.2.1_Fabric_1.21.jar --outputdir /tmp/putithere

**Comment by krispyking24** [comment]
i got cfr-0.152.jar from downloading it from releases page

**Comment by leibnitz27** [comment]
Java -jar jarname

**Comment by krispyking24** [comment]
thank you for the quick response, i'll try it when i get home and sorry for my late response
