### ISSUE TITLE
Unable to use CFR

### ISSUE THREAD

**Issue by thefourtheye** [leibnitz27/cfr#38]
```
➜ java -jar ~/Downloads/cfr-0.148.jar <jar file to be decompiled>
no main manifest attribute, in /Users/<username>/Downloads/cfr-0.148.jar
➜
```

Simple usage guide in README or project documentation would help.

**Comment by leibnitz27** [comment]
That's very odd, there's quite definitely a manifest.    

Please check the jar you have matches the md5 on the website.  

Also try without a jar file


```
lee@rick:/mnt/c/Downloads$ java -jar cfr-0.148.jar
CFR 0.148

java -jar CFRJAR.jar class_or_jar_file [method] [options]

Parameter error : Insufficient unqualified parameters - provide at least one filename.

Please specify '--help' to get option list, or '--help optionname' for specifics, eg
   --help pullcodecase
```

```
C:\Downloads>java -jar cfr-0.148.jar
CFR 0.148

java -jar CFRJAR.jar class_or_jar_file [method] [options]

Parameter error : Insufficient unqualified parameters - provide at least one filename.

Please specify '--help' to get option list, or '--help optionname' for specifics, eg
   --help pullcodecase
```

**Comment by leibnitz27** [comment]
for ref : 44d5bc109860c486c8d89b58abe853d6

**Comment by thefourtheye** [comment]
I tried without the jar file, the result is still the same

```
➜  Downloads java -jar cfr-0.148.jar
no main manifest attribute, in cfr-0.148.jar
➜  Downloads java -jar cfr-0.148.jar --help
no main manifest attribute, in cfr-0.148.jar
➜  Downloads java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-macosx) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-macosx) (build 25.222-b10, mixed mode)
➜  Downloads
```

**Comment by leibnitz27** [comment]
What is the md5 & size of the jar you have?   can you please check it matches https://www.benf.org/other/cfr/cfr-0.148.jar ?

**Comment by leibnitz27** [comment]
You should be able to see the main class in the manifest here:

lee@rick:/mnt/c/Downloads$ unzip -p cfr-0.148.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.6.0
Built-By: Lee
Build-Jdk: 10.0.2
Specification-Title: cfr
Specification-Version: 0.148
Implementation-Title: cfr
Implementation-Version: 0.148
Implementation-Vendor-Id: org.benf
Main-Class: org.benf.cfr.reader.Main

**Comment by leibnitz27** [comment]
ping @thefourtheye - tbh I suspect you have a bad jar - would be handy if you can try the above.

**Comment by leibnitz27** [comment]
Closing as not reproducible and dead (pls reopen if you have additional info)

**Comment by thefourtheye** [comment]
@leibnitz27 You were right. Looks like the jar file was not correct. I wonder how `java` managed to parse it.

I should have updated this thread sooner, please accept my sincere apology.

**Comment by leibnitz27** [comment]
No problem, thanks for following up!
