### ISSUE TITLE
Local variable order is inconsistent

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#41]
### Description
It appears CFR is not writing local variable declarations in a consistent order. When decompiling the same jar file multiple times it is very likely that for some methods local variable declarations moved to different lines, sometimes also causing their names to change (if CFR is choosing the names) since their declaration order changed.

This is quite irritating when decompiling different versions of a jar and seeing changes where there aren't actually any.

### Potential cause
It appears the following line is the cause for this:
https://github.com/leibnitz27/cfr/blob/591af0db149779832180363472b442339a0c4318/src/org/benf/cfr/reader/bytecode/analysis/parse/utils/scope/AbstractLValueScopeDiscoverer.java#L159

It creates a `HashMap` which is not using the insertion order when iterating over its entries.
However, I am not familiar enough with the project to be completely sure.

**Comment by leibnitz27** [comment]
Ah, nice.  Interestingly, that doesn't seem to manifest on JRE10, but reliably flips with JRE6.  Good spot.

**Comment by leibnitz27** [comment]
https://github.com/leibnitz27/cfr_tests/blob/master/src_6/org/benf/cfr/tests/VarOrderingTest.java
