### ISSUE TITLE
Suggestion: Write functional array construction as method reference

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#42]
Java allows writing method references for array "constructors", e.g.:
```
IntFunction<byte[]> factory = byte[]::new;
```

Currently CFR decompiles this as
```
n -> new byte[n]
```

This is still valid Java code, however it might be nice if it would write method references instead.

**Comment by leibnitz27** [comment]
Hmm - it's a bit worse than that - recent versions of javac use x$0.  Which is a perfectly legitimate identifier, but rather gross.
