### ISSUE TITLE
Classpath issue processing WAR.

### ISSUE THREAD

**Issue by DoctorJava** [leibnitz27/cfr#44]

**Comment by leibnitz27** [comment]
Hey - as far as I know (and I have many tests) enums (unless obfuscated) decompile fine.

Please provide a sample class file (that you have rights to) or a test to demonstrate, or I won't be able to do anything with this issue.

**Comment by DoctorJava** [comment]
CFR doesn't seem to handle ENUMs.  I added a public ENUM to the attached Book.java model class, The resulting decompiled file (Book_decompiled.java) shows an error and is an invalid java file. I am attempting to run javadocs on the decompiled files, but this causes the javadocs to fail.
[Book.java.txt](https://github.com/leibnitz27/cfr/files/3833618/Book.java.txt)
[Book_decompiled.java.txt](https://github.com/leibnitz27/cfr/files/3833626/Book_decompiled.java.txt)

[Book.class.txt](https://github.com/leibnitz27/cfr/files/3833632/Book.class.txt)
[Book$SECTION.class.txt](https://github.com/leibnitz27/cfr/files/3833633/Book.SECTION.class.txt)

**Comment by leibnitz27** [comment]
Ah.  Compiled with eclipse.  Might as well be obfuscated :)

It changes code patterns all the time, and though CFR does cover most of them, looks like you've found a new one.  Thanks!

**Comment by DoctorJava** [comment]
Yep, I used the Eclipse Export -> WAR file menu for this file.  I will try building with gradle and let you know what happens.

**Comment by DoctorJava** [comment]
I don't understand the Eclipse issues, but I got the same problem when doing a Gradle Build in Eclipse.  Thanks for the quick response.

**Comment by leibnitz27** [comment]
Hey - which version are you using?  I just tried with 0.148, jre 10, and got

```
/*
 * Decompiled with CFR 0.148.
 */
package net.jakartaee.tools.sample.model;

import java.io.PrintStream;

public class Book {
    private String _title;
    private String _author;
    private int _year;
    private SECTION _section;

    public Book() {
    }

    public Book(String title, String author, int year, SECTION section) {
        this._title = title;
        this._author = author;
        this._year = year;
        this._section = section;
    }

    public String getTitle() {
        return this._title;
    }

    public void setTitle(String title) {
        this._title = title;
    }

    public String getAuthor() {
        return this._author;
    }

    public void setAuthor(String author) {
        this._author = author;
    }

    public int getYear() {
        return this._year;
    }

    public void setYear(int year) {
        this._year = year;
    }

    public SECTION getSection() {
        return this._section;
    }

    public void setSection(SECTION section) {
        this._section = section;
        switch (section) {
            case FICTION: {
                System.out.println("Got FICTION");
                break;
            }
            default: {
                System.out.println("Got Non-Fiction");
            }
        }
    }
    public static enum SECTION {
        FICTION,
        NON_FICTION,
        BIOGRAPHY;

    }

}
```

**Comment by leibnitz27** [comment]
(same result with 1.6 and java 13)

**Comment by leibnitz27** [comment]
oh, ok, you're running off a local build. 

Something very funky is going on if you can't load 
```
 * Could not load the following classes:
 *  net.jakartaee.tools.sample.model.Book
 *  net.jakartaee.tools.sample.model.Book$SECTION
```

Suggest you try with an official release, and check you don't have an issue with master.

**Comment by DoctorJava** [comment]
I don't think this is an Eclipse issue.  I think it is a CLASSPATH problem with CFR decompiling .war files.  Here is a simple webapp war file.  It was created with eclipse Dynamic web app, with the attached two java files.
[SimpleWebapp.war.txt](https://github.com/leibnitz27/cfr/files/3839023/SimpleWebapp.war.txt)
[GreetingServlet.java.txt](https://github.com/leibnitz27/cfr/files/3839027/GreetingServlet.java.txt)
[Greeting.java.txt](https://github.com/leibnitz27/cfr/files/3839029/Greeting.java.txt)

Greeting.java (decompiled)
/*
 * Decompiled with CFR 0.148.
 * 
 * Could not load the following classes:
 *  model.Greeting
 *  model.Greeting$TYPE
 */
package model;

import model.Greeting;

/*
 * Exception performing whole class analysis ignored.
 */
public class Greeting {
    private String _name;
    private TYPE _type;
    private static /* synthetic */ int[] $SWITCH_TABLE$model$Greeting$TYPE;

    public Greeting(String _name, TYPE _type) {
        this._name = _name;
        this._type = _type;
    }

    /*
     * Exception decompiling
     */
    public String toString() {
        // This method has failed to decompile.  When submitting a bug report, please provide this stack trace, and (if you hold appropriate legal rights) the relevant class file.
        // java.lang.NullPointerException
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchEnumRewriter.tryRewriteEclipse(SwitchEnumRewriter.java:234)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchEnumRewriter.tryRewrite(SwitchEnumRewriter.java:151)
        // org.benf.cfr.reader.bytecode.analysis.opgraph.op4rewriters.SwitchEnumRewriter.rewrite(SwitchEnumRewriter.java:85)
        // org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:782)
        // org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:238)
        // org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:183)
        // org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:96)
        // org.benf.cfr.reader.entities.Method.analyse(Method.java:397)
        // org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:964)
        // org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:855)
        // org.benf.cfr.reader.Driver.doJarVersionTypes(Driver.java:242)
        // org.benf.cfr.reader.Driver.doJar(Driver.java:125)
        // org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:65)
        // org.benf.cfr.reader.Main.main(Main.java:48)
        throw new IllegalStateException("Decompilation failed");
    }

    static /* synthetic */ int[] $SWITCH_TABLE$model$Greeting$TYPE() {
        if ($SWITCH_TABLE$model$Greeting$TYPE != null) {
            return $SWITCH_TABLE$model$Greeting$TYPE;
        }
        int[] arrn = new int[TYPE.values().length];
        try {
            arrn[TYPE.GOODBYE.ordinal()] = 2;
        }
        catch (NoSuchFieldError noSuchFieldError) {}
        try {
            arrn[TYPE.HELLO.ordinal()] = 1;
        }
        catch (NoSuchFieldError noSuchFieldError) {}
        $SWITCH_TABLE$model$Greeting$TYPE = arrn;
        return arrn;
    }

**Comment by leibnitz27** [comment]
Aha! This makes perfect sense.   Yep, I'm processing war files wrong.   Should be a simple fix....

**Comment by leibnitz27** [comment]
There could still be further improvement - processing embedded jars in wars to improve analysis of calls....
