### ISSUE TITLE
CFR adds not needed imports

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#49]
# CFR version
0.149-SNAPSHOT (commit bfb754c)

# Description
CFR adds not needed imports when the return type of a method is not referenced or for lambdas.

# Example code
```
import java.util.regex.Pattern;

public class LambdaImportTest {
    public void test() {
        /*
         * Unnecessarily imports:
         * - java.util.regex.Matcher
         * - java.util.function.Function;
         * - java.util.regex.MatchResult
         */
        Pattern.compile("test").matcher("test").replaceFirst(result -> "");
    }
}
```

**Comment by leibnitz27** [comment]
Fascinating - I had a really complicated way of doing this, which could be massively simplified to be more accurate \o/
