### ISSUE TITLE
CFR incorrectly uses `true` for binary operators on ints

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#51]
# CFR version
0.149-SNAPSHOT (commit bfb754c)

# Description
CFR incorrectly uses `true` for binary operators on ints (and possibly longs as well) in some cases, e.g.:
```
int i = 0;
i |= true;
```

# Example code
```
public class CompoundAssignmentTest {
    public int test() {
        int i = 0;
        int h = 1;
        i = h & 1;
        
        return i;
    }
    
    public int test2() {
        int i = 0;
        i |= 1;
        
        return i;
    }
}
```

**Comment by leibnitz27** [comment]
Oh, that's a pain.  Bool and int are indistiguishable at the bytecode level (a bool *is* an int) apart from in signatures.   That's why you'll occasionally see this.  Nice spot.
