### ISSUE TITLE
Access from multiple nested inner classes is incorrect

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#53]
# CFR version
0.149-SNAPSHOT (commit 06539a4)

# Description
When decompiling classes containing multiple nested inner classes which access the field of the enclosing class, the code generated by CFR is invalid:
```
A.this.NestedInnerClasses.this.str
```

# Example code
```
public class NestedInnerClasses {
    private String str;
    
    class A {
        class B {
            String doSomething() {
                return str;
            }
        }
    }
}
```

**Comment by leibnitz27** [comment]
yet another wacky ecj issue.
