### ISSUE TITLE
Ternary ? 1 : 0 is incorrectly replaced with boolean

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#58]
# CFR version
0.149-SNAPSHOT (commit 06539a4)

# Description
Similar to #51
When a ternary returns either 1 or 0, it is omitted when a numeric value is expected:
`(float) (b ? 1 : 0)` becomes `(float) b`

# Example code
```
public class TernaryBoolean {
    float test(boolean b) {
        return b ? 1 : 0;
    }
}
```

**Comment by leibnitz27** [comment]
Hi - can you provide an example for this?

java -jar c:\Users\Lee\website\other\cfr\cfr-0.148.jar org\benf\cfr\tests\CastTest24.class
/*
 * Decompiled with CFR 0.148.
 */
package org.benf.cfr.tests;

public class CastTest24 {
    float test1(boolean b) {
        return b ? 1.0f : 0.0f;
    }

    int test2(boolean b) {
        return b ? 1 : 0;
    }

    short test3(boolean b) {
        return b ? (short)1 : 0;
    }

    long test4(boolean b) {
        return b ? 1L : 0L;
    }

    byte test5(boolean b) {
        return b ? (byte)1 : 0;
    }
}

**Comment by leibnitz27** [comment]
Oh.  It's bloody eclipse.

Right. 

Do me a favour, don't raise any more issues based on eclipse for a bit, I'm going to add ecj to the test set.
 (drop me a mail and I'll let you know when I'm done).

**Comment by Marcono1234** [comment]
Sorry, I assumed it would affect `javac` as well, but did not test it.
Alright I will stop reporting issues for now then, and sorry for reporting so many.

**Comment by leibnitz27** [comment]
Don't be sorry, it's super useful and appreciated!  
I just suspect that adding ecj to my semi-automated tests will save you generating several issues by hand.

Sigh.  Trivial fix, and useful to have in as it's perfectly legit code, but what was ecj thinking? ;)

javac
```
  float test1(boolean);
    Code:
       0: iload_1
       1: ifeq          8
       4: fconst_1
       5: goto          9
       8: fconst_0
       9: freturn
```

ecj

```
  float test1(boolean);
    Code:
       0: iload_1
       1: ifeq          8
       4: iconst_1
       5: goto          9
       8: iconst_0
       9: i2f
      10: freturn
```
