### ISSUE TITLE
Local variables of different type are reused

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#61]
# CFR version
0.149-SNAPSHOT (commit fdd0a63)

# Description
CFR reuses local variables of different types which results in invalid code.
So far I was only able to reproduce this using `javac`, but not using ecj.
Code produced by CFR:
```
int[] arrn;
for (int i = 0; i < 10; ++i) {
    arrn = "test";
}
int[] arrn2 = new int[1];
arrn = new int[1];
```

# Example code
```
public class LocalVarReuse {
    void test() {
        for (int i = 0; i < 10; i++) {
            // CFR incorrectly moves aArr up and reuses it for this string
            String s = "test";
        }
        
        int[] aArr = new int[1];
        int[] bArr = new int[1];
    }
}
```

**Comment by leibnitz27** [comment]
In general - I need to take a few weeks, and rewrite the SSA pass, with a view to doing much better lifetime discovery. 

(caveat - lifetime discovery is hard :( ).

The 'perfect' fix here (Don't allow String/int[] to resolve at all) breaks https://github.com/leibnitz27/cfr_tests/blob/master/src_6/org/benf/cfr/tests/Objection2.java
so I'm not going to do it for now, instead allowing them to collide at Object.

**Comment by Marcono1234** [comment]
Thanks. I have decompiled a large project again and there was one change where it now due to this commit started reusing a local variable (and has the same issues as described below). Though maybe that is acceptable.

However, it appears CFR does not emit the required casts when the variable is used. Is that intended for now?

E.g. (`javac 11.0.5`):
```
public class LocalVarReuse {
    void test() {
        for (int i = 0; i < 10; i++) {
            String s = "test";
        }
        
        int[] aArr = new int[1];
        int[] bArr = new int[1];
        aArr[0] = 1;
        bArr[0] = 1;
    }
}
```

Decompiled:
```
public class LocalVarReuse {
    void test() {
        Object object;
        for (int i = 0; i < 10; ++i) {
            object = "test";
        }
        int[] arrn = new int[1];
        object = new int[1];
        arrn[0] = 1;
        // Missing cast and wrong value type
        object[0] = true;
    }
}
```

**Comment by Marcono1234** [comment]
@leibnitz27 should I create a separate issue for this?

**Comment by Marcono1234** [comment]
@leibnitz27 do you want a separate issue or do you want to reopen this issue?
