### ISSUE TITLE
OverloadMethodSet.callsCorrectEntireMethod is possibly not working correctly

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#63]
# CFR version
0.149-SNAPSHOT (commit a37e9e5)

# Description
It appears `OverloadMethodSet.callsCorrectEntireMethod` is not working correctly. Decompiling the same class which calls [Log4j's `Logger.error(String, Supplier<?>...)`](https://logging.apache.org/log4j/2.0/log4j-api/apidocs/org/apache/logging/log4j/Logger.html#error-java.lang.String-org.apache.logging.log4j.util.Supplier...-) multiple times occasionally emits the creation of a new array instead of directly passing the supplier as varargs.

It looks like changing the following to an ordered set makes the output predictable:
https://github.com/leibnitz27/cfr/blob/2aefadeb7d0076e0b1c8e338d97e62bc706b6a09/src/org/benf/cfr/reader/entities/classfilehelpers/OverloadMethodSet.java#L131

However, the underlying bug is very likely in the logic of that method. Changing the set to an ordered one would just make that method rely on the declaration order of the methods to check, which is probably not the intended behavior. I assume the following code is faulty:
https://github.com/leibnitz27/cfr/blob/2aefadeb7d0076e0b1c8e338d97e62bc706b6a09/src/org/benf/cfr/reader/entities/classfilehelpers/OverloadMethodSet.java#L199-L239

**Comment by leibnitz27** [comment]
Can you provide a sample that manifests this?
Thanks.

**Comment by Marcono1234** [comment]
Yes, sure. I do not have the rights to share the code where I have first seen this, but I was able to recreate this now.
It might only affect varargs, at least this is the only case where I have seen it.

Code to decompile:
```
import java.util.function.Supplier;

public interface CorrectMethodCallTest {
    void call(CharSequence s, Object o);
    void call(String s, Object o);
    void call(String s, Supplier<?>... supplier);
    
    default void test() {
        call("test", () -> "test");
    }
}
```
And insert the following at OverloadMethodSet.java line 138 to always randomly shuffle it and not depend on hash code values:
```
List<MethodData> possibleMatchesL = new ArrayList<MethodData>(possibleMatches);
Collections.shuffle(possibleMatchesL);
possibleMatches = new LinkedHashSet<MethodData>(possibleMatchesL);
```

Then decompile the class multiple times. Sometimes you should see `this.call("test", new Supplier[]{() -> "test"});`.

*Note:* It appears the usage of a set at OverloadMethodSet.java line 131 also makes little sense because MethodData does not override `equals` or `hashCode`.

**Comment by leibnitz27** [comment]
Re your note - not overriding equals or hashcode is deliberate, this means this set is a referential equality set.

Great spot on the ordering - while the fix *actually* fixes it, this sort of thing shouldn't have any non-determinism in it, so I'll change that anyway.
