### ISSUE TITLE
Cannot evaluate *.toString()

### ISSUE THREAD

**Issue by baishi6582** [leibnitz27/cfr#65]
![image](https://user-images.githubusercontent.com/12906496/70546444-4426b880-1baa-11ea-955f-ee8b699a18a7.png)

**Comment by leibnitz27** [comment]
Where is this?  Are you inside a debugger?  
In which case no, you absolutely can't expect to be able to evaluate toString on all objects.  

Can you reproduce this on the command line?

**Comment by leibnitz27** [comment]
(To rephrase - if you're inside a debugger, I expect that you can handle viewing intermediate state of partially generated objects.  It's not expected that all objects are capable of toStringing at all possible states.   If you're debugging, investigate members).

**Comment by leibnitz27** [comment]
ping @baishi6582

**Comment by leibnitz27** [comment]
Closing this, as it doesn't add value in current state and has been abandoned.   Feel free to reopen if you have additional info.
