### ISSUE TITLE
org.benf.cfr.reader.util.ConfusedCFRException

### ISSUE THREAD

**Issue by ghxstdev** [leibnitz27/cfr#69]
Unfortunately I don't think I hold the appropriate legal rights, to post the class file.
I can however post the hash of the apk / dex / class file if you would like me to.

```
         * org.benf.cfr.reader.util.ConfusedCFRException: Started 2 blocks at once
         * org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.getStartingBlocks(Op04StructuredStatement.java:397)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.buildNestedBlocks(Op04StructuredStatement.java:472)
         * org.benf.cfr.reader.bytecode.analysis.opgraph.Op03SimpleStatement.createInitialStructuredBlock(Op03SimpleStatement.java:619)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:751)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:239)
         * org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:184)
         * org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:94)
         * org.benf.cfr.reader.entities.Method.analyse(Method.java:394)
         * org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:958)
         * org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:849)
         * org.benf.cfr.reader.Driver.doJarVersionTypes(Driver.java:245)
         * org.benf.cfr.reader.Driver.doJar(Driver.java:128)
         * org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:65)
         * org.benf.cfr.reader.Main.main(Main.java:49)
         */

```

If you have any idea what might be causing this let me know and I can try to make a test case.

**Comment by Marcono1234** [comment]
Might be caused by nested try-catch blocks, CFR has currently some issues with them. See also #52.
Could you try decompiling the class in question using a different decompiler (or simply using [Bytecode Viewer](https://github.com/Konloch/bytecode-viewer)) and check if the failing method does indeed contain try-catch or try-with-resources statements?

**Comment by leibnitz27** [comment]
fwiw - nested 'try-with-resources' blocks are not really nested try-catch blocks, they're *significantly* nastier.  (have a look at what happens when you use `--tryresources false --decodefinally false`)

**Comment by leibnitz27** [comment]
You're likely to get reasonable looking code with `--ignoreexceptionsalways true` though there's always danger that there's useful behaviour inside exception handlers.

If it works with that, then this issue is already covered by existing ones, so probably closable as a dupe.

Thanks.

**Comment by ghxstdev** [comment]
Closing this until I can provide a more detailed issue. Until then I believe this to be covered by existing ones as indicated by @leibnitz27 .
