### ISSUE TITLE
Classes with invalid identifiers don't get renamed

### ISSUE THREAD

**Issue by pavlukivan** [leibnitz27/cfr#71]
So a class with a name "0" can exist even when `--renameillegalidents` is true, despite not having members with illegal identifiers.

**Comment by pavlukivan** [comment]
I've fixed it on my local branch, however I'm not a Java programmer and I don't wanna spend my time learning how to use obfuscators to change the class name to such name, so I can't provide tests. If that's ok, I can make a pull request, even if it will not be merged for a while (Until someone makes the tests).

**Comment by leibnitz27** [comment]
You'd be surprised how painful the general solution was TBH :/
