### ISSUE TITLE
Handle unverifiable jumps into the middle of instructions.

### ISSUE THREAD

**Issue by leibnitz27** [leibnitz27/cfr#75]
https://anthony.som.codes/blog/2019-12-30-jvm-hackery-noverify/ (
@half-cambodian-hacker-man ) points out some fun stuff allowing jumps to vector into the middle of other byte code.

**Comment by leibnitz27** [comment]
```
  public static int foo();
    Code:
       0: nop
       1: nop
       2: goto          6
       5: sipush        8
       8: istore        0
      10: getstatic     #14                 // Field java/lang/System.out:Ljava/io/PrintStream;
      13: iload         0
      15: invokevirtual #8                  // Method java/io/PrintStream.println:(I)V
      18: sipush        1
      21: ireturn

```
Now gives

    /*
     * Handled unverifiable bytecode (illegal jump).
     */
    public static int foo() {
        int n = 5;
        System.out.println(n);
        return 1;
    }

**Comment by leibnitz27** [comment]
And here are a couple of examples.

[NoVerify.class.zip](https://github.com/leibnitz27/cfr/files/4039487/NoVerify.class.zip)
[NoVerify2.class.zip](https://github.com/leibnitz27/cfr/files/4039489/NoVerify2.class.zip)

**Comment by half-cambodian-hacker-man** [comment]
Does this work for conditional branches?

**Comment by leibnitz27** [comment]
Should do.  Feel free to try to break it ;)

**Comment by leibnitz27** [comment]
(And if you do, pls provide class file ;) )
