### ISSUE TITLE
CFR v0.148 crashes when empty string is stored as method generics attribute

### ISSUE THREAD

**Issue by ItzSomebody** [leibnitz27/cfr#77]
@Col-E found this one.

Setting the method generics attribute to an empty UTF8 string results in the following to occur:
```
org.benf.cfr.reader.util.CannotLoadClassException: Test.class - java.lang.StringIndexOutOfBoundsException: String index out of range: 0
```

[example.zip](https://github.com/leibnitz27/cfr/files/4051923/example.zip)

**Comment by leibnitz27** [comment]
Nice.  Signature vs Descriptor is a tricky one - without them you can't recreate generics at all, but you can't even *fully* check the signature matches the descriptor, because of artificial signatures in enums.

I could probably stand to be a bit more paranoid here too.
