### ISSUE TITLE
Lambda variable types are not emitted for ambiguous calls

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#78]
# CFR version
0.149-SNAPSHOT (commit 22b3529)

# Description
Lambda variable types are not emitted when method calls are ambiguous.

Source code:
```
import java.util.function.Function;
import java.util.function.IntFunction;

class Test {
    void use(IntFunction<?> factory) { }
    Object use(Function<String, ?> factory) {
        return null;
    }

    Object consume(int i) {
        return null;
    }
    Object consume(String s) {
        return null;
    }
    
    void test() {
        // Must specify variable types otherwise calls are ambiguous
        use((String s) -> null);
        use((String s) -> consume(s));
    }
}
```

Decompiled output:
```
import java.util.function.Function;
import java.util.function.IntFunction;

class Test {
    Test() {
    }

    void use(IntFunction<?> intFunction) {
    }

    Object use(Function<String, ?> function) {
        return null;
    }

    Object consume(int n) {
        return null;
    }

    Object consume(String string) {
        return null;
    }

    void test() {
        // javac refuses to compile this because it is ambiguous
        this.use(string -> null);
        // javac thinks IntFunction is used and complains about invalid cast
        this.use(string -> this.consume((String)string));
    }
}
```

**Comment by leibnitz27** [comment]
Test slightly tweaked for extra psycho.

`
package org.benf.cfr.tests;

import java.util.function.DoubleBinaryOperator;
import java.util.function.Function;
import java.util.function.IntBinaryOperator;
import java.util.function.IntFunction;
import java.util.function.LongToDoubleFunction;

class LambdaTest42 {
    void use(IntFunction<?> factory) { }
    void use(IntBinaryOperator factory) { }
    void use(DoubleBinaryOperator factory) { }
    void use(LongToDoubleFunction factory) { }
    Object use(Function<String, ?> factory) {
        return null;
    }
    void use(IntFunction<?> factory, int x) { }
    void use(IntBinaryOperator factory, int x) { }
    void use(DoubleBinaryOperator factory, int x) { }
    void use(LongToDoubleFunction factory, int x) { }
    Object use(Function<String, ?> factory, int x) {
        return null;
    }

    int consume(int i, int j) {
        return i;
    }
    double consume(double i, double j) {
        return i;
    }
    Object consume(int i) {
        return null;
    }
    double consume(long i) {
        return i;
    }
    Object consume(String s) {
        return null;
    }

    void test() {
        // Must specify variable types otherwise calls are ambiguous
        use((String s) -> null);
        use((String s) -> consume(s));
        use((int s) -> consume(s));
        use((long s) -> consume(s));
        use((int a, int b) -> consume(a, b));
        use((double a, double b) -> consume(a,b));
        use((String s) -> null, 1);
        use((String s) -> consume(s), 2);
        use((int s) -> consume(s),3);
        use((long s) -> consume(s), 4);
        use((int a, int b) -> consume(a, b), 5);
        use((double a, double b) -> consume(a,b), 6);
    }
}
`

**Comment by leibnitz27** [comment]
Test slightly tweaked for extra psycho....

```
package org.benf.cfr.tests;

import java.util.function.DoubleBinaryOperator;
import java.util.function.Function;
import java.util.function.IntBinaryOperator;
import java.util.function.IntFunction;
import java.util.function.LongToDoubleFunction;

class LambdaTest42 {
    void use(IntFunction<?> factory) { }
    void use(IntBinaryOperator factory) { }
    void use(DoubleBinaryOperator factory) { }
    void use(LongToDoubleFunction factory) { }
    Object use(Function<String, ?> factory) {
        return null;
    }
    void use(IntFunction<?> factory, int x) { }
    void use(IntBinaryOperator factory, int x) { }
    void use(DoubleBinaryOperator factory, int x) { }
    void use(LongToDoubleFunction factory, int x) { }
    Object use(Function<String, ?> factory, int x) {
        return null;
    }

    int consume(int i, int j) {
        return i;
    }
    double consume(double i, double j) {
        return i;
    }
    Object consume(int i) {
        return null;
    }
    double consume(long i) {
        return i;
    }
    Object consume(String s) {
        return null;
    }

    void test() {
        // Must specify variable types otherwise calls are ambiguous
        use((String s) -> null);
        use((String s) -> consume(s));
        use((int s) -> consume(s));
        use((long s) -> consume(s));
        use((int a, int b) -> consume(a, b));
        use((double a, double b) -> consume(a,b));
        use((String s) -> null, 1);
        use((String s) -> consume(s), 2);
        use((int s) -> consume(s),3);
        use((long s) -> consume(s), 4);
        use((int a, int b) -> consume(a, b), 5);
        use((double a, double b) -> consume(a,b), 6);
    }
}

```
