### ISSUE TITLE
NonStaticLifter can change order of initialisers with side effects

### ISSUE THREAD

**Issue by grahamedgecombe** [leibnitz27/cfr#8]
NonStaticLifter lifts initialisers even if the fields are declared in a different order to the order of the initialisation code in the constructor. This changes the semantics of the program if the initialisers have side effects.

Here's a simple test case:

```
public class Test {
    private static int printA() {
        System.out.println("A");
        return 0;
    }

    private static int printB() {
        System.out.println("B");
        return 0;
    }

    private int a;
    private int b;

    private Test() {
        b = printB();
        a = printA();
    }

    public static void main(String[] args) {
        new Test();
    }
}
```

It prints B followed by A:

```
$ java Test
B
A
$ 
````

This is how cfr decompiles the code - note that printA/B are now called in the opposite order:

```
/*
 * Decompiled with CFR 0.145.
 */
import java.io.PrintStream;

public class Test {
    private int a = Test.printA();
    private int b = Test.printB();

    private static int printA() {
        System.out.println("A");
        return 0;
    }

    private static int printB() {
        System.out.println("B");
        return 0;
    }

    private Test() {
    }

    public static void main(String[] arrstring) {
        new Test();
    }
}
```

It incorrectly prints A followed by B:

```
$ java Test
A
B
$ 
```

**Comment by leibnitz27** [comment]
Added MemberInitOrderTest,2,3 to http://github.com/leibnitz27/cfr_tests

**Comment by leibnitz27** [comment]
FWIW, the fix leaves *slightly* ugly code, in as much as it pulls b up, and leaves a in the constructor.  
I don't really like that, however short of detecting patterns in the two partitions....
The whole lifting can always be disabled with a flag if it offends.
