### ISSUE TITLE
Malformed code when blocks are used

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#81]
# CFR version
0.149-SNAPSHOT (commit 22b3529)

# Description
CFR emits code with many casts or malformed code when blocks are used to reduce the scope of a variable. This might be the same as or similar to #61.

Source:
```
class Test {
    void casting() {
        {
            String s = "";
            s.isEmpty();
            s.length();
            s.substring(0, 1);
        }
        
        Integer i = 1;
        i.intValue();
        Integer.toHexString(i);
    }
    
    void useInt(int i) { }
    void useShort(short s) { }
    void useChar(char c) { }
    void useByte(byte b) { }
    void useBoolean(boolean b) { }
    
    void testChar() {
        {
            short s = (short) -32767;
            useShort(s);
        }
        
        char c = 1;
        useChar(c);
    }
    
    void testByte() {
        {
            int i = 32767;
            useInt(i);
        }
        
        byte b = 1;
        useByte(b);
    }
    
    void testBoolean() {
        {
            int i = 32767;
            useInt(i);
        }
        
        boolean b = true;
        useBoolean(b);
    }
}
```

Decompiled output:
```
class Test {
    Test() {
    }

    void casting() {
        Object object = "";
        ((String)object).isEmpty();
        ((String)object).length();
        ((String)object).substring(0, 1);
        object = 1;
        ((Integer)object).intValue();
        Integer.toHexString((Integer)object);
    }

    void useInt(int n) {
    }

    void useShort(short s) {
    }

    void useChar(char c) {
    }

    void useByte(byte by) {
    }

    void useBoolean(boolean bl) {
    }

    void testChar() {
        char c = '\uffff8001';
        this.useShort((short)c);
        c = '\u0001';
        this.useChar(c);
    }

    void testByte() {
        byte by = 32767;
        this.useInt(by);
        by = 1;
        this.useByte(by);
    }

    void testBoolean() {
        boolean bl = BADBOOL 32767;
        this.useInt((int)bl);
        bl = true;
        this.useBoolean(bl);
    }
}
```

**Comment by leibnitz27** [comment]
Indeed - this is slot re-use, and it's a b*tch.   It's worth an explanation, perhaps,

CFR performs (effictively) reverse SSA (ok, that's a bit hand-wavey, but the lexicon for decompilers isn't as well formed as that of compilers :) ) - and we break the SSA at the point where we determine the lifetime of the variable ends.

However, slot re-use isn't immediately obvious to spot (the below is an easy case, but given for information, I don't need suggestions on how to solve it).

```
{
 { 
  Object a = null; // slot 2
  a = "Fred";
  System.out.println(a);
 }
 {
  WonderFoo b = new WonderFoo();  // also slot 2
  System.out.println(b);
 }
}
```

compared to
```
  {
     Object foo = null;
     foo = "Fred";
     System.out.println(foo);
     foo = new WonderFoo();
     System.out.println(jim);
  }
```

There's no actual difference (*) (* if you discount the potentially-lying metadata.)

It's especially fun, because you can take this to extremes - each assignment that explicitly truncates a lifetime _could_ be a new variable.  There's no (* above) way to tell.

So I have all sorts of crappy heuristics.  Yay.  The specific 'out of range' test cases above should be spottable though, so nice ;).

**Comment by leibnitz27** [comment]
@Marcono1234  - what compiler did you use here?  I get (trimmed to illegal portions of above) for jdk6-13 + ecj8.

https://github.com/leibnitz27/cfr_tests/blob/master/src_6/org/benf/cfr/tests/MalformedBlockTest1a.java

```
  void testBoolean();
    Code:
       0: sipush        32767
       3: istore_1
       4: aload_0
       5: iload_1
       6: invokevirtual #23                 // Method useInt:(I)V
       9: iconst_1
      10: istore_1
      11: aload_0
      12: iload_1
      13: invokevirtual #25                 // Method useBoolean:(Z)V
      16: return
```

[MalformedBlockTest1a.class.zip](https://github.com/leibnitz27/cfr/files/4105671/MalformedBlockTest1a.class.zip)


```
class MalformedBlockTest1 {
    MalformedBlockTest1() {
    }

    void useInt(int i) {
    }

    void useShort(short s) {
    }

    void useChar(char c) {
    }

    void useByte(byte b) {
    }

    void useBoolean(boolean b) {
    }

    void testChar() {
        short s = -32767;
        this.useShort(s);
        char c = '\u0001';
        this.useChar(c);
    }

    void testByte() {
        int i = 32767;
        this.useInt(i);
        byte b = 1;
        this.useByte(b);
    }

    void testBoolean() {
        int i = 32767;
        this.useInt(i);
        boolean b = true;
        this.useBoolean(b);
    }
}
```

**Comment by Marcono1234** [comment]
Originally I used `javac 11.0.5` and I am getting the same byte code. It appears the difference is the LocalVariableTable. I have compiled the code without specifying debugging options (i.e. the same as `-g:lines`). However it appears you have the LocalVariableTable (`-g:vars`). When I compile using that and then decompile I get correct results as well.

**Comment by leibnitz27** [comment]
Aha - makes sense.  Thanks.
