### ISSUE TITLE
Casts are omitted when casting floating point and integers

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr#86]
# CFR version
0.149-SNAPSHOT (commit 22b3529)

# Compiler
javac 11.0.5

# Description
Some necessary casts are omitted when casting values to floating point and integer types.

Source:
```
class FloatingPointCasting {
    long getLong() {
        return 9223372036854775806L;
    }
    
    void test() {
        long b = (long) (double) getLong();
        System.out.println(b == getLong()); // Prints "false"
    }
    
    public static void main(String ... args) {
        new FloatingPointCasting().test();
    }
}
```

Decompiled output:
```
class FloatingPointCasting {
    FloatingPointCasting() {
    }

    long getLong() {
        return 0x7FFFFFFFFFFFFFFEL;
    }

    void test() {
        long l = this.getLong();
        System.out.println(l == this.getLong());
    }

    public static void main(String ... arrstring) {
        new CharCasting().test();
    }
}
```

**Comment by leibnitz27** [comment]
Damn.  You're on form this week.  I can't keep up. ;)

It's fun to notice that constant folding means this isn't always an issue (see https://github.com/leibnitz27/cfr_tests/blob/master/src_6/org/benf/cfr/tests/FloatingPointCasting2.java )

Anyway, fixed ;)
