### ISSUE TITLE
Recover full method path

### ISSUE THREAD

**Issue by lab313ru** [leibnitz27/cfr#9]
It there any way to specify full method path decompilation?

I mean, for now it shows only `myClass.myMethod()` call, but it will be great also to show it like this:
`com.mycom.myClass.myMethod()`.

**Comment by leibnitz27** [comment]
It's possible (with a little hacking) - out of interest what's the reason you want to do this?   

You can get the behaviour you want by always returning type.getRawName() from https://github.com/leibnitz27/cfr/blob/33216277ae3b61a9d2b3f912d9ed91a3e698d536/src/org/benf/cfr/reader/state/TypeUsageInformationImpl.java#L192

As an option ("don't explicitly import anything") it would lead to hideous code, so I'm not keen to do it unless I can think of a good reason! :)

**Comment by lab313ru** [comment]
The reason is:
jar-file is obfuscated, some classes in subfolders have the same names (it may remember the `duplicate field names` problem), and there are strings-deobfuscation methods, all of them have different variation for every class.

Then imagine situation like this:
- `MsgBox(o.decode("\xab\xcd"))` (com.sub1.o)
- `MsgBox(o.decode("\xcc\xdd"))` (com.sub2.o)

I want to write some deobfuscator (in Python), but to understand which deobfuscator was used I need to restore full type path.

**Comment by leibnitz27** [comment]
Handled with a general 'don't import this' filter, using the same regex filter as elsewhere in options.

--importfilter "util"  <-- only generate imports for classes that match 'util'.
--importfilter "!util" <-- only generate imports for classes that *don't* match 'util'.
--importfilter "!(util|lang|^com.sun)" <--- etc etc.

**Comment by lab313ru** [comment]
Thank you!

Lee Benfield <notifications@github.com> 31 июля 2019 г. 9:39:44 написал:
